import type { CaseStudy, Question } from "../questions";
import { multi, single } from "./builders";
import { expansionSources as sources } from "./sources";

export const expandedCaseStudies: CaseStudy[] = [
  {
    id: "litware",
    title: "Case study: Litware Contact Center",
    subtitle: "A privacy-aware multilingual service assistant",
    tabs: [
      {
        label: "Overview",
        content: [
          "Litware operates customer-service centers for several European utility companies. Agents handle billing questions, service interruptions, appointment changes, and safety incidents through voice and web channels. Customers frequently alternate languages, quote account details, and upload short policy documents while a case is open.",
          "Litware is replacing a collection of scripted bots with a Microsoft Foundry application. A triage agent identifies the customer need, retrieves approved guidance, and delegates to billing or operations specialists. Human representatives remain accountable for account changes and emergency escalation.",
          "The first release supports English, French, German, and Italian. It must provide interim speech transcripts during calls, translate language-homogeneous segments when necessary, and preserve identifiers such as meter codes without treating them as ordinary natural-language phrases.",
        ],
      },
      {
        label: "Data and interaction",
        content: [
          "Approved procedures are stored in an enterprise Azure AI Search index with text chunks, vectors, effective dates, jurisdiction, utility company, and source URLs. A caller can also upload a temporary PDF that applies only to the current case and is not yet present in the enterprise index.",
          "The application keeps the active case number and recent tool results in conversation state. Customers can optionally save durable communication preferences, such as a preference for concise written summaries, but those memories must be isolated per user and removable on request.",
          "Transcripts can contain names, addresses, telephone numbers, account identifiers, and free-form descriptions of medical or financial circumstances. Ordinary operational traces must not receive raw personal information when redacted text is sufficient for diagnosing routing or latency.",
          "Some callers switch languages inside a single utterance. Litware has observed incorrect or incomplete output when a mixed-language sentence is submitted as one Translator request. The client can segment an utterance and associate a supported source language with each segment before translation.",
        ],
      },
      {
        label: "Speech and tools",
        content: [
          "A Custom Speech model improves recognition of local street names and utility terminology. Its production endpoint serves interactive calls, while overnight quality analysis uses batch transcription over recordings retained under the applicable customer contract.",
          "Operations tracks every model's transcription expiration date. The team knows an expired model produces different behavior for a custom endpoint and a batch request, so the deployment runbook must detect loss of domain accuracy as well as explicit request failures.",
          "Billing and appointment APIs are described by OpenAPI documents with unique operation IDs and bounded schemas. Lookup operations are read-only. Changes require the representative to see the exact account, action, and arguments before approving the tool invocation.",
          "Uploaded case documents use the agent file-search tool and a case-specific vector store. Enterprise procedures remain in the centrally managed Azure AI Search index because they require metadata filters, scheduled ingestion, and shared lifecycle management across utilities.",
        ],
      },
      {
        label: "Governance and operations",
        content: [
          "Production workloads use managed identities and narrowly scoped roles. The backend passes an end-user identity when accessing durable memory. A new conversation receives a new case context, and the service must never rely on a static memory scope shared by all customers.",
          "Preproduction evaluation uses multilingual calls, noisy audio, mixed-language utterances, rare street names, outdated procedures, missing evidence, malformed tool arguments, and rejected account changes. Thresholds cover speech accuracy, retrieval relevance, groundedness, task adherence, PII handling, and tool-input accuracy.",
          "After release, Litware samples production interactions for continuous evaluation and correlates failures with traces for speech, retrieval, model, and tool spans. Audit records retain approvals and safe identifiers, while sensitive contents are minimized. Alerts distinguish quality drift from latency, authorization, quota, and model-lifecycle problems.",
          "Release drills simulate an expired speech model, an unavailable vector store, a revoked workload role, a throttled model deployment, and a failed approval callback. Operators must identify the responsible component from safe telemetry, preserve idempotency during recovery, and verify that a fallback never turns an unapproved account change into an executed action.",
        ],
      },
    ],
  },
  {
    id: "adventureworks",
    title: "Case study: Adventure Works Media",
    subtitle: "Grounded multimodal production for outdoor equipment",
    tabs: [
      {
        label: "Overview",
        content: [
          "Adventure Works creates product education and campaign media for bicycles, helmets, clothing, and repair equipment. Each campaign includes approved photographs, technical diagrams, draft videos, narration, disclosure text, and partner-submitted PDFs. The team publishes in several markets and accessibility formats.",
          "A Microsoft Foundry solution will help editors discover assets, answer visual questions, create localized variations, and assemble compliance evidence. The system can recommend and generate drafts, but a designer and compliance reviewer must approve high-impact material before publishing credentials become available.",
          "Editors want the assistant to distinguish visible facts from interpretation. If a photograph omits a component, contains unreadable text, or is too blurred to support a conclusion, the assistant must identify the limitation rather than invent a product feature or safety claim.",
        ],
      },
      {
        label: "Ingestion and grounding",
        content: [
          "PDF manuals contain paragraphs, tables, diagrams, and scanned pages. The Azure AI Search indexer must extract text and normalized embedded images, run OCR where required, split long content, generate vectors, and project parent and chunk identifiers into the retrieval index.",
          "The retrieval index also stores product code, market, language, approval status, effective date, and source asset URL. Product codes require exact lexical matching, while conceptual questions need hybrid search, semantic ranking, and a query-time vectorizer that matches the indexing embedding model.",
          "Partner content is untrusted. Printed text in an image or a PDF can attempt to instruct the agent to ignore its policies. Detected document attacks exclude the affected material from grounding, but they do not replace visual harm classification, output moderation, or human review.",
          "Content Understanding analyzers extract structured campaign fields and layout-aware representations from variable documents, images, audio, and video. Stable standardized forms may continue using Document Intelligence where a supported prebuilt or trained document model is the more direct fit.",
        ],
      },
      {
        label: "Generation and editing",
        content: [
          "Designers generate concept images from text and approved reference media. Some requests replace only a background, so the source image and a compatible mask define the editable region. Unmasked products, labels, and required disclosures should remain recognizable.",
          "E-commerce layouts sometimes require a transparent background. The generation request must use a model, output format, and background setting that support transparency. Encoded image output is decoded to bytes before being stored with its prompt, sources, deployment, and parameters.",
          "Video drafts are processed as time-aligned segments. Reviewers need spoken text, on-screen disclosures, visible products, important scene changes, and source timestamps. A summary without segment provenance is insufficient for verifying a claim or locating a required correction.",
          "Alt text is written for the purpose and context of each image. It communicates meaningful visible information, avoids unsupported marketing claims, and records uncertainty when a necessary detail cannot be verified. Longer text is not automatically more accessible.",
        ],
      },
      {
        label: "Quality and release",
        content: [
          "The evaluation set includes low-resolution product photographs, exact part codes, scanned diagrams, transparent output, masked edits, multilingual narration, unsafe content, indirect prompt attacks, and visually ambiguous scenes. Reviewers score visual fidelity, groundedness, accessibility, schema accuracy, safety, latency, and provenance completeness.",
          "Application and publishing identities are separate. Retrieval and generation components cannot publish assets. The controlled publishing component accepts only approved, versioned outputs and an idempotency identifier, preventing a network retry from producing duplicate publication jobs.",
          "Production traces correlate ingestion, retrieval, generation, safety, and review operations without copying unnecessary protected content. Failed evaluation samples enter a regression set, and every changed analyzer, prompt, model, or index must pass the applicable release thresholds before promotion.",
          "Every market keeps an approval matrix for products, disclosures, source assets, and publishing destinations. A release rehearsal includes stale documents, expired approvals, missing masks, invalid transparency formats, model throttling, and a duplicated publish request. The team verifies that each failure remains attributable and that no retry can cross the publishing boundary without the original approved version.",
        ],
      },
    ],
  },
];

const litwareDomain = "Implement text analysis solutions" as const;
const visionDomain = "Implement computer vision solutions" as const;

export const expandedCaseStudyQuestions: Question[] = [
  single({
    id: 204,
    section: "litware",
    domain: litwareDomain,
    objective: "Translate mixed-language calls through segmentation",
    difficulty: "Advanced",
    skillId: "text.translation",
    topicTags: ["case-study", "translator", "mixed-language"],
    variantGroup: "litware-mixed-language-translation",
    stem: "What should Litware do before translating an utterance that contains multiple languages?",
    options: [
      "Submit the whole utterance with no source language and rely on automatic detection",
      "Split it into language-homogeneous segments and translate each with the intended source language",
      "Convert the audio to a transparent image and use multimodal OCR",
      "Store it in durable memory and wait for the memory update delay",
    ],
    correct: 1,
    explanation: "The documented Translator mitigation is to avoid a mixed-language sentence as one request. Segmenting the utterance and supplying each segment's intended source language addresses the known incomplete-translation behavior.",
    source: sources.translatorIssues,
  }),
  single({
    id: 205,
    section: "litware",
    domain: litwareDomain,
    objective: "Plan for Custom Speech expiration across transcription routes",
    difficulty: "Advanced",
    skillId: "text.speech",
    topicTags: ["case-study", "custom-speech", "lifecycle"],
    variantGroup: "litware-speech-expiration-runbook",
    stem: "Which runbook behavior correctly covers Litware's expired Custom Speech model?",
    options: [
      "Expect the interactive endpoint to fall back to a same-locale base model and expect batch requests naming the expired model to fail with 4xx",
      "Expect both routes to retrain the expired model automatically before accepting new audio",
      "Expect batch transcription to fall back silently while the custom endpoint always fails with 5xx",
      "Expect both routes to preserve the expired model indefinitely because it was once deployed",
    ],
    correct: 0,
    explanation: "The custom endpoint and batch route have different documented outcomes. Monitoring must therefore detect domain-accuracy regression after endpoint fallback as well as explicit batch client errors.",
    source: sources.customSpeechLifecycle,
  }),
  single({
    id: 206,
    section: "litware",
    domain: "Implement generative AI and agentic solutions",
    objective: "Separate conversation state, durable memory, and uploaded knowledge",
    difficulty: "Intermediate",
    skillId: "genai.agents",
    topicTags: ["case-study", "conversation", "memory", "file-search"],
    variantGroup: "litware-agent-state-selection",
    stem: "Where should Litware retain the active case number that must disappear when the current support conversation ends?",
    options: [
      "In the current conversation state",
      "In a static durable-memory scope shared across all customers",
      "In the enterprise procedure index as a searchable document",
      "In every specialist agent's system instructions",
    ],
    correct: 0,
    explanation: "The case number is transient session context and belongs in the active conversation. Durable memory is for approved cross-session information, while retrieval indexes and system instructions are not per-conversation state stores.",
    source: sources.memory,
  }),
  multi({
    id: 207,
    section: "litware",
    domain: "Plan and manage an Azure AI solution",
    objective: "Minimize sensitive transcript data while preserving diagnostics",
    difficulty: "Advanced",
    skillId: "plan.observability",
    topicTags: ["case-study", "pii", "tracing"],
    variantGroup: "litware-pii-observability-controls",
    stem: "Which two controls best satisfy Litware's transcript diagnostic requirements?",
    options: [
      "Run PII detection before sending transcript text to ordinary diagnostic logs",
      "Keep correlation IDs and latency spans needed to connect the redacted interaction to its operations",
      "Copy raw transcripts into every agent span so each team has independent evidence",
      "Disable all traces because privacy and observability cannot coexist",
    ],
    correct: [0, 1],
    explanation: "Early redaction reduces disclosure while correlation and operational spans preserve root-cause analysis. Litware does not need raw sensitive text in every span, and privacy controls do not require abandoning observability.",
    source: sources.pii,
  }),
  multi({
    id: 208,
    section: "litware",
    domain: "Implement generative AI and agentic solutions",
    objective: "Use separate retrieval paths for temporary and enterprise knowledge",
    difficulty: "Advanced",
    skillId: "genai.rag",
    topicTags: ["case-study", "file-search", "azure-ai-search"],
    variantGroup: "litware-dual-retrieval-path",
    stem: "Which two retrieval choices align with Litware's requirements?",
    options: [
      "Attach a case-specific vector store to file search for the temporary uploaded PDF",
      "Store every enterprise procedure as durable user memory",
      "Use the managed Azure AI Search index for shared procedures and its metadata filters",
      "Place the full enterprise corpus in the system message for every call",
    ],
    correct: [0, 2],
    explanation: "File search directly supports uploaded case documents, while the enterprise index supports shared ingestion, filtering, and lifecycle management. Memory and oversized system messages are not replacements for governed retrieval.",
    source: sources.fileSearch,
  }),
  {
    id: 209,
    section: "litware",
    domain: litwareDomain,
    objective: "Avoid an expired model in a batch transcription payload",
    difficulty: "Advanced",
    type: "code",
    language: "python",
    skillId: "text.speech",
    topicTags: ["case-study", "batch-transcription", "model-lifecycle"],
    variantGroup: "litware-batch-model-payload",
    lastVerified: "2026-09-01",
    stem: "Complete the payload-building logic. When the custom model is expired, omitting the model property lets batch transcription use the latest base model.",
    code: `payload = {
    "locale": "en-US",
    "contentUrls": recording_urls,
}

if {{model_is_usable}}:
    payload[{{model_property}}] = model_url`,
    blanks: [
      { id: "model_is_usable", label: "Include only a usable custom model", options: [
        { id: "expired", text: "model_expired" },
        { id: "usable", text: "not model_expired" },
        { id: "always", text: "True" },
      ] },
      { id: "model_property", label: "Batch model property", options: [
        { id: "locale", text: "\"locale\"" },
        { id: "model", text: "\"model\"" },
        { id: "display", text: "\"displayName\"" },
      ] },
    ],
    correct: { model_is_usable: "usable", model_property: "model" },
    explanation: "A batch request that explicitly names an expired model fails. Litware can include the model property only while the custom model is usable; otherwise omitting it selects the latest base model.",
    source: sources.customSpeechLifecycle,
  },
  {
    id: 210,
    section: "litware",
    domain: "Plan and manage an Azure AI solution",
    objective: "Match contact-center failures to observability evidence",
    difficulty: "Intermediate",
    type: "matrix",
    skillId: "plan.observability",
    topicTags: ["case-study", "evaluation", "tracing", "lifecycle"],
    variantGroup: "litware-operational-evidence",
    lastVerified: "2026-09-01",
    stem: "For each symptom, select the evidence Litware should inspect first.",
    rows: [
      { id: "groundedness", text: "Sampled production groundedness declines" },
      { id: "latency", text: "One call has unexpectedly slow retrieval" },
      { id: "speech", text: "Domain terms suddenly transcribe like the generic locale model" },
    ],
    columns: [
      { id: "evaluation", text: "Continuous evaluation results" },
      { id: "trace", text: "The correlated retrieval span" },
      { id: "expiration", text: "Custom Speech model and endpoint lifecycle status" },
    ],
    correct: { groundedness: "evaluation", latency: "trace", speech: "expiration" },
    explanation: "Evaluation identifies population-level quality drift, a correlated span localizes an individual latency problem, and lifecycle status explains a sudden same-locale base-model fallback in interactive speech recognition.",
    source: sources.continuousEvaluation,
  },
  single({
    id: 211,
    section: "adventureworks",
    domain: visionDomain,
    objective: "Refuse unsupported visual conclusions",
    difficulty: "Intermediate",
    skillId: "vision.understanding",
    topicTags: ["case-study", "visual-grounding", "uncertainty"],
    variantGroup: "adventureworks-insufficient-visual-evidence",
    stem: "An editor asks whether an unseen rear brake assembly matches a safety specification. The photograph shows only the front of the bicycle. What should the assistant do?",
    options: [
      "Answer from the visible front brake because both assemblies are normally identical",
      "State that the rear assembly cannot be verified and request evidence that shows it",
      "Generate a rear view and compare the generated part",
      "Use the product's marketing category as proof of compliance",
    ],
    correct: 1,
    explanation: "The required component is not visible, so the assistant must identify the evidence gap. A generated view, analogous component, or marketing category cannot establish the condition of the real rear assembly.",
    source: sources.multimodal,
  }),
  single({
    id: 212,
    section: "adventureworks",
    domain: visionDomain,
    objective: "Constrain a product-background replacement",
    difficulty: "Intermediate",
    skillId: "vision.generation",
    topicTags: ["case-study", "mask", "image-editing"],
    variantGroup: "adventureworks-masked-background-edit",
    stem: "Which input best preserves the approved bicycle while replacing only the background?",
    options: [
      "A text-only description of the bicycle and permission to regenerate every pixel",
      "The approved source image plus a mask identifying the background as editable",
      "A cropped logo and the final publication URL",
      "The source image converted to OCR text before generation",
    ],
    correct: 1,
    explanation: "The source image supplies the approved subject and the mask bounds the editable region. Text-only regeneration and OCR do not preserve the source pixels or constrain the edit to the background.",
    source: sources.imageGeneration,
  }),
  single({
    id: 213,
    section: "adventureworks",
    domain: "Implement information extraction solutions",
    objective: "Expose embedded PDF images for OCR enrichment",
    difficulty: "Intermediate",
    skillId: "extraction.search",
    topicTags: ["case-study", "normalized-images", "ocr"],
    variantGroup: "adventureworks-normalized-images",
    stem: "What configuration makes embedded manual diagrams available at the normalized image path for downstream OCR?",
    options: [
      "A non-none imageAction such as generateNormalizedImages",
      "A semantic configuration that lists only the document key",
      "A query vectorizer with image extraction disabled",
      "A scoring profile that boosts PDF file size",
    ],
    correct: 0,
    explanation: "The indexer or Document Extraction skill must generate normalized images. Semantic ranking, vectorization, and scoring profiles operate on indexed fields and do not extract embedded image content.",
    source: sources.documentExtractionSkill,
  }),
  multi({
    id: 214,
    section: "adventureworks",
    domain: "Plan and manage an Azure AI solution",
    objective: "Separate generation from publishing authority",
    difficulty: "Advanced",
    skillId: "plan.security",
    topicTags: ["case-study", "least-privilege", "approval"],
    variantGroup: "adventureworks-publishing-boundary",
    stem: "Which two controls enforce Adventure Works' publishing boundary?",
    options: [
      "Keep publishing credentials only in the controlled publishing component",
      "Require the approved asset version and reviewer decision before publishing",
      "Give the generation agent publishing credentials so it can recover from review delays",
      "Treat a model self-critique as the compliance approval event",
    ],
    correct: [0, 1],
    explanation: "Separating credentials limits the generation component's authority, and an explicit approval tied to the version gates publication. Self-critique is evaluation evidence, not human authorization.",
    source: sources.foundryRbac,
  }),
  multi({
    id: 215,
    section: "adventureworks",
    domain: "Implement generative AI and agentic solutions",
    objective: "Layer retrieval and attack detection for untrusted media",
    difficulty: "Advanced",
    skillId: "genai.rag",
    topicTags: ["case-study", "prompt-shields", "hybrid-search"],
    variantGroup: "adventureworks-secure-grounding",
    stem: "Which two actions best protect and ground the assistant when it uses partner documents?",
    options: [
      "Exclude material identified as a document attack from the grounding context",
      "Use hybrid retrieval with filters for approval status, market, and effective date",
      "Allow instructions inside retrieved PDFs to override the system message when semantically relevant",
      "Disable source URLs so the model cannot reveal which evidence it used",
    ],
    correct: [0, 1],
    explanation: "Document-attack detection prevents malicious grounding content from controlling the agent, while filtered hybrid retrieval selects relevant approved evidence. Retrieved instructions remain untrusted, and source links support verification.",
    source: sources.promptShields,
  }),
  {
    id: 216,
    section: "adventureworks",
    domain: visionDomain,
    objective: "Request a transparent generated image output",
    difficulty: "Advanced",
    type: "code",
    language: "json",
    skillId: "vision.generation",
    topicTags: ["case-study", "transparent-background", "image-generation"],
    variantGroup: "adventureworks-transparent-image-json",
    lastVerified: "2026-09-01",
    stem: "Complete the compatible output settings for a generated product cutout with transparency.",
    code: `{
  "model": "gpt-image-1",
  "prompt": "Approved red touring bicycle, isolated product cutout",
  "background": "{{background}}",
  "output_format": "{{output_format}}"
}`,
    blanks: [
      { id: "background", label: "Background mode", options: [
        { id: "opaque", text: "opaque" },
        { id: "transparent", text: "transparent" },
        { id: "auto_color", text: "auto-color" },
      ] },
      { id: "output_format", label: "Transparency-compatible format", options: [
        { id: "jpeg", text: "jpeg" },
        { id: "txt", text: "txt" },
        { id: "png", text: "png" },
      ] },
    ],
    correct: { background: "transparent", output_format: "png" },
    explanation: "A transparent background requires the transparent setting and a format such as PNG that can carry an alpha channel. JPEG does not preserve transparency, and text is not an image output format.",
    source: sources.imageGeneration,
  },
  {
    id: 217,
    section: "adventureworks",
    domain: "Implement information extraction solutions",
    objective: "Order multimodal ingestion for grounded retrieval",
    difficulty: "Advanced",
    type: "order",
    skillId: "extraction.search",
    topicTags: ["case-study", "ingestion", "vectorization", "provenance"],
    variantGroup: "adventureworks-multimodal-ingestion-order",
    lastVerified: "2026-09-01",
    stem: "Arrange the ingestion stages for scanned manuals used by the assistant.",
    options: [
      { id: "extract", text: "Extract document content and generate normalized images" },
      { id: "enrich", text: "Run OCR or other required enrichment over the normalized images" },
      { id: "chunk", text: "Create bounded text chunks and their embeddings" },
      { id: "index", text: "Project chunks, vectors, filters, and parent provenance into the search index" },
    ],
    correct: ["extract", "enrich", "chunk", "index"],
    explanation: "Extraction exposes text and images, enrichment obtains needed visual text, chunking and embedding prepare retrieval units, and projections persist both searchable data and its parent provenance.",
    source: sources.integratedVectorization,
  },
];
