import type { Question } from "../questions";
import { expansionSources as sources } from "./sources";

const multilingualContext = "A multilingual contact-center assistant processes live calls, translates language-homogeneous segments, and creates account-change requests. The service must protect personal information, preserve domain speech accuracy, and prevent the agent from changing an account without representative approval.";
const ragContext = "A research agent grounds answers in an Azure AI Search index containing approved and untrusted partner documents. Access is tenant-specific. Every answer must cite current evidence, and text embedded in retrieved documents must not alter the agent's system behavior.";
const mediaContext = "A media agent generates product images and prepares them for publication. Designers may replace a bounded background, compliance reviewers approve high-impact assets, and the generation component must never publish directly.";

export const decisionSequenceQuestions: Question[] = [
  {
    id: 218,
    section: "decision",
    decisionSetId: "multilingual-contact-center",
    domain: "Implement text analysis solutions",
    objective: "Mitigate mixed-language Translator input",
    difficulty: "Advanced",
    type: "decision",
    skillId: "text.translation",
    topicTags: ["decision-sequence", "translator", "mixed-language"],
    variantGroup: "decision-multilingual-segmentation",
    lastVerified: "2026-09-01",
    context: multilingualContext,
    stem: "The team splits mixed-language utterances into language-homogeneous segments and supplies each segment's intended source language to Translator. Does this solution help meet the translation requirement?",
    correct: "yes",
    explanation: "Translator documents mixed-language sentences as a known limitation. Segmenting the input and specifying the intended source language are documented mitigations for incorrect or incomplete translation.",
    source: sources.translatorIssues,
  },
  {
    id: 219,
    section: "decision",
    decisionSetId: "multilingual-contact-center",
    domain: "Plan and manage an Azure AI solution",
    objective: "Prevent sensitive transcript content from entering ordinary logs",
    difficulty: "Advanced",
    type: "decision",
    skillId: "plan.observability",
    topicTags: ["decision-sequence", "pii", "logging"],
    variantGroup: "decision-multilingual-pii-logging",
    lastVerified: "2026-09-01",
    context: multilingualContext,
    stem: "The team writes every raw transcript to Application Insights before running PII detection so investigators can reconstruct calls. Does this solution meet the privacy requirement?",
    correct: "no",
    explanation: "The design propagates sensitive content before applying the stated protection. PII detection and minimization should occur before ordinary diagnostic logging whenever redacted content and safe identifiers are sufficient.",
    source: sources.pii,
  },
  {
    id: 220,
    section: "decision",
    decisionSetId: "multilingual-contact-center",
    domain: "Implement generative AI and agentic solutions",
    objective: "Gate consequential account changes",
    difficulty: "Intermediate",
    type: "decision",
    skillId: "genai.tools",
    topicTags: ["decision-sequence", "approval", "tool-call"],
    variantGroup: "decision-multilingual-account-approval",
    lastVerified: "2026-09-01",
    lifecycle: "preview",
    context: multilingualContext,
    stem: "The workflow pauses before the account-change tool, displays the exact customer, operation, and arguments, and proceeds only after representative approval. Does this solution meet the control requirement?",
    correct: "yes",
    explanation: "The approval is placed before the consequential call and covers the exact action that will execute. This provides a meaningful human-in-the-loop control instead of a notification after the change.",
    source: sources.workflows,
  },
  {
    id: 221,
    section: "decision",
    decisionSetId: "secure-rag-ingestion",
    domain: "Implement information extraction solutions",
    objective: "Apply tenant filtering before vector scoring",
    difficulty: "Advanced",
    type: "decision",
    skillId: "extraction.search",
    topicTags: ["decision-sequence", "security-filter", "vector-search"],
    variantGroup: "decision-rag-pre-filter",
    lastVerified: "2026-09-01",
    context: ragContext,
    stem: "The query applies the caller's tenant authorization filter before vector scoring selects candidate documents. Does this solution help meet the isolation requirement?",
    correct: "yes",
    explanation: "Applying the authorization filter before scoring keeps documents from other tenants out of the candidate set and therefore out of the grounding context. Post-answer filtering would be too late.",
    source: sources.searchFilters,
  },
  {
    id: 222,
    section: "decision",
    decisionSetId: "secure-rag-ingestion",
    domain: "Implement generative AI and agentic solutions",
    objective: "Block indirect prompt attacks in grounding content",
    difficulty: "Advanced",
    type: "decision",
    skillId: "genai.rag",
    topicTags: ["decision-sequence", "prompt-shields", "indirect-injection"],
    variantGroup: "decision-rag-document-attack",
    lastVerified: "2026-09-01",
    context: ragContext,
    stem: "The team treats every retrieved instruction as trusted whenever semantic ranking assigns it a high score. Does this solution meet the system-behavior requirement?",
    correct: "no",
    explanation: "Retrieval relevance does not establish instruction trust. Partner documents remain untrusted data and should be screened for document attacks; their text must not override higher-priority system behavior.",
    source: sources.promptShields,
  },
  {
    id: 223,
    section: "decision",
    decisionSetId: "secure-rag-ingestion",
    domain: "Plan and manage an Azure AI solution",
    objective: "Correlate evaluation regressions with traces",
    difficulty: "Intermediate",
    type: "decision",
    skillId: "plan.observability",
    topicTags: ["decision-sequence", "evaluation", "tracing"],
    variantGroup: "decision-rag-evaluation-trace-correlation",
    lastVerified: "2026-09-01",
    context: ragContext,
    stem: "The team continuously evaluates sampled production answers and retains correlated retrieval traces for root-cause analysis. Does this solution support detection and diagnosis of grounding regressions?",
    correct: "yes",
    explanation: "Continuous evaluation detects changes in response quality, while correlated retrieval traces expose the evidence and operations behind affected interactions. Together they support both monitoring and diagnosis.",
    source: sources.continuousEvaluation,
  },
  {
    id: 224,
    section: "decision",
    decisionSetId: "governed-media-release",
    domain: "Implement computer vision solutions",
    objective: "Constrain a bounded image edit with a mask",
    difficulty: "Intermediate",
    type: "decision",
    skillId: "vision.generation",
    topicTags: ["decision-sequence", "mask", "image-editing"],
    variantGroup: "decision-media-mask",
    lastVerified: "2026-09-01",
    context: mediaContext,
    stem: "For a background-only replacement, the team sends the approved source image and a compatible mask that identifies only the background as editable. Does this solution support the preservation requirement?",
    correct: "yes",
    explanation: "The source preserves the approved subject and the mask bounds the region that generation may change. This directly supports background replacement without unconstrained regeneration of the product.",
    source: sources.imageGeneration,
  },
  {
    id: 225,
    section: "decision",
    decisionSetId: "governed-media-release",
    domain: "Plan and manage an Azure AI solution",
    objective: "Separate generation and publication identities",
    difficulty: "Advanced",
    type: "decision",
    skillId: "plan.security",
    topicTags: ["decision-sequence", "least-privilege", "publishing"],
    variantGroup: "decision-media-publishing-identity",
    lastVerified: "2026-09-01",
    context: mediaContext,
    stem: "The generation component receives the publishing credential so it can publish automatically when its self-critique score exceeds the review threshold. Does this solution meet the authorization requirement?",
    correct: "no",
    explanation: "The design collapses the required security boundary and substitutes model self-assessment for human approval. Publishing authority should remain with the controlled component that validates an explicit approval event.",
    source: sources.foundryRbac,
  },
  {
    id: 226,
    section: "decision",
    decisionSetId: "governed-media-release",
    domain: "Implement generative AI and agentic solutions",
    objective: "Require explicit human approval for publication",
    difficulty: "Advanced",
    type: "decision",
    skillId: "genai.tools",
    topicTags: ["decision-sequence", "human-approval", "idempotency"],
    variantGroup: "decision-media-approved-version",
    lastVerified: "2026-09-01",
    lifecycle: "preview",
    context: mediaContext,
    stem: "The publishing workflow accepts only an approved asset version and an idempotency identifier after designer and compliance approval. Does this solution help meet the release requirement?",
    correct: "yes",
    explanation: "The explicit approvals gate the consequential action, the version binds approval to exact content, and the idempotency identifier protects the publishing call from duplicate execution during retries.",
    source: sources.workflows,
  },
];
