import type { Question } from "../../questions";
import { multi, single } from "../builders";
import { expansionSources as sources } from "../sources";

const domain = "Implement information extraction solutions" as const;

export const extractionQuestions: Question[] = [
  single({
    id: 197,
    domain,
    objective: "Pair chunking and embedding skills for integrated vectorization",
    difficulty: "Intermediate",
    skillId: "extraction.search",
    topicTags: ["integrated-vectorization", "text-split", "embedding"],
    variantGroup: "integrated-vectorization-skill-pair",
    stem: "An Azure AI Search indexer must split long documents into chunks and generate an Azure OpenAI vector for every chunk. Which skill pair directly implements those two stages?",
    options: [
      "Text Split skill followed by Azure OpenAI Embedding skill",
      "OCR skill followed by Sentiment skill",
      "Document Extraction skill followed by Key Phrase Extraction skill",
      "Custom Web API skill followed by Semantic ranking",
    ],
    correct: 0,
    explanation: "The Text Split skill performs chunking and the Azure OpenAI Embedding skill converts each chunk into a vector during indexing. Semantic ranking is a query-time ranking capability rather than an embedding skill.",
    source: sources.integratedVectorization,
  }),
  single({
    id: 198,
    domain,
    objective: "Generate normalized images for downstream OCR enrichment",
    difficulty: "Intermediate",
    skillId: "extraction.search",
    topicTags: ["normalized-images", "ocr", "indexer"],
    variantGroup: "indexer-normalized-images-image-action",
    stem: "A Blob indexer must expose embedded document images at /document/normalized_images/* for downstream image skills. What should be configured?",
    options: [
      "Set imageAction to generateNormalizedImages in the applicable extraction or indexer configuration",
      "Set parsingMode to text and disable every image action",
      "Add a semantic configuration named normalized_images",
      "Store base64 images in the search document key field",
    ],
    correct: 0,
    explanation: "A non-none imageAction such as generateNormalizedImages produces the normalized image collection used by downstream enrichment. Query ranking and key-field choices do not extract embedded images.",
    source: sources.documentExtractionSkill,
  }),
  single({
    id: 199,
    domain,
    objective: "Choose Content Understanding for variable multimodal extraction",
    difficulty: "Intermediate",
    skillId: "extraction.content",
    topicTags: ["content-understanding", "document-intelligence", "schema"],
    variantGroup: "variable-multimodal-extraction-tool-choice",
    stem: "An intake package can contain free-form PDFs, photographs, audio, and video, and the output must follow one custom business schema. Which service is the better primary fit?",
    options: [
      "A fixed-layout Document Intelligence custom template model for every media type",
      "Content Understanding with a schema-based multimodal analyzer",
      "Translator document translation without an extraction schema",
      "Azure AI Search semantic ranking without an ingestion pipeline",
    ],
    correct: 1,
    explanation: "Content Understanding analyzers are designed for schema-based extraction across documents, images, audio, and video. Document Intelligence remains strong for supported document-centric and stable-layout workloads but is not a universal multimedia parser.",
    source: sources.contentUnderstanding,
  }),
  multi({
    id: 200,
    domain,
    objective: "Configure a complete integrated vectorization pipeline",
    difficulty: "Advanced",
    skillId: "extraction.search",
    topicTags: ["indexer", "vectorizer", "embedding-model"],
    variantGroup: "integrated-vectorization-model-consistency",
    stem: "Which two configurations are required for consistent integrated vectorization at indexing and query time?",
    options: [
      "Use a skillset that chunks content and generates vectors during indexing",
      "Use unrelated embedding models for indexing and query-time vectorization to increase diversity",
      "Configure a vectorizer on the index that matches the embedding model used for indexed content",
      "Remove the vector field and store vectors only in the semantic configuration",
    ],
    correct: [0, 2],
    explanation: "The indexer-driven skillset creates chunk vectors, and the index vectorizer converts text queries with the same embedding model. Mismatched vector spaces cannot be compared meaningfully, and semantic configuration does not store vectors.",
    source: sources.integratedVectorization,
  }),
  {
    id: 201,
    section: "general",
    domain,
    objective: "Declare chunking and embedding skills in a Search skillset",
    difficulty: "Advanced",
    type: "code",
    language: "json",
    skillId: "extraction.search",
    topicTags: ["skillset", "text-split", "azure-openai-embedding"],
    variantGroup: "integrated-vectorization-skillset-json",
    lastVerified: "2026-09-01",
    stem: "Complete the skill types for a pipeline that chunks document content and then creates an Azure OpenAI vector for each chunk.",
    code: `{
  "name": "rag-skillset",
  "skills": [
    {
      "@odata.type": "{{split_skill}}",
      "context": "/document",
      "textSplitMode": "pages"
    },
    {
      "@odata.type": "{{embedding_skill}}",
      "context": "/document/pages/*",
      "deploymentName": "text-embedding-3-small"
    }
  ]
}`,
    blanks: [
      { id: "split_skill", label: "Chunking skill type", options: [
        { id: "split", text: "#Microsoft.Skills.Text.SplitSkill" },
        { id: "ocr", text: "#Microsoft.Skills.Vision.OcrSkill" },
        { id: "merge", text: "#Microsoft.Skills.Text.MergeSkill" },
      ] },
      { id: "embedding_skill", label: "Embedding skill type", options: [
        { id: "language", text: "#Microsoft.Skills.Text.LanguageDetectionSkill" },
        { id: "embedding", text: "#Microsoft.Skills.Text.AzureOpenAIEmbeddingSkill" },
        { id: "sentiment", text: "#Microsoft.Skills.Text.V3.SentimentSkill" },
      ] },
    ],
    correct: { split_skill: "split", embedding_skill: "embedding" },
    explanation: "SplitSkill chunks the document text, and AzureOpenAIEmbeddingSkill generates vectors over those chunks. OCR, merge, language-detection, and sentiment skills do not create this chunk-and-vector sequence.",
    source: sources.integratedVectorization,
  },
  {
    id: 202,
    section: "general",
    domain,
    objective: "Order integrated vectorization components",
    difficulty: "Intermediate",
    type: "order",
    skillId: "extraction.search",
    topicTags: ["integrated-vectorization", "indexer", "query-vectorizer"],
    variantGroup: "integrated-vectorization-pipeline-order",
    lastVerified: "2026-09-01",
    stem: "Arrange the indexing path from source content to searchable chunk vectors.",
    options: [
      { id: "retrieve", text: "The indexer retrieves content from the configured data source" },
      { id: "chunk", text: "The chunking skill divides extracted content into bounded units" },
      { id: "embed", text: "The embedding skill creates a vector for each chunk" },
      { id: "project", text: "Index projections or field mappings write chunks and vectors to the target index" },
    ],
    correct: ["retrieve", "chunk", "embed", "project"],
    explanation: "The indexer drives data retrieval, enrichment first creates chunks and then their vectors, and mappings or projections persist the enriched outputs. Query-time vectorization occurs later when users search.",
    source: sources.integratedVectorization,
  },
  {
    id: 203,
    section: "general",
    domain,
    objective: "Match extraction requirements to pipeline outputs",
    difficulty: "Intermediate",
    type: "match",
    skillId: "extraction.documents",
    topicTags: ["normalized-images", "structured-output", "markdown"],
    variantGroup: "extraction-output-selection",
    lastVerified: "2026-09-01",
    stem: "Match each downstream requirement to the most useful extraction output.",
    prompts: [
      { id: "ocr", text: "Run OCR over images embedded in an indexed PDF" },
      { id: "fields", text: "Send validated invoice values to a line-of-business API" },
      { id: "rag", text: "Preserve headings and tables for grounded document reasoning" },
    ],
    choices: [
      { id: "normalized", text: "normalized_images collection" },
      { id: "json", text: "Structured JSON matching the business schema" },
      { id: "markdown", text: "Layout-aware Markdown representation" },
      { id: "quota", text: "Search service quota metrics" },
    ],
    correct: { ocr: "normalized", fields: "json", rag: "markdown" },
    explanation: "Normalized images feed visual enrichment, structured JSON supports deterministic business integration, and layout-aware Markdown preserves useful document organization for reasoning. Quota metrics are operational rather than extracted content.",
    source: sources.contentUnderstanding,
  },
];
