import type { Question } from "../../questions";
import { multi, single } from "../builders";
import { expansionSources as sources } from "../sources";

const domain = "Implement generative AI and agentic solutions" as const;

export const generativeQuestions: Question[] = [
  single({
    id: 167,
    domain,
    objective: "Isolate durable agent memory by end user",
    difficulty: "Advanced",
    skillId: "genai.agents",
    topicTags: ["agent-memory", "user-isolation", "scope"],
    variantGroup: "memory-per-user-scope",
    stem: "A backend calls the same prompt agent for many customers. Each customer may keep durable preferences, but no preference can be visible to another customer. Which memory-tool scope should be configured?",
    options: [
      "A single static scope equal to the agent version name",
      "The literal scope {{$conversationId}} with no user identity header",
      "The per-user scope {{$userId}}, with the backend sending the appropriate memory user identity",
      "A scope based only on the Foundry project resource ID",
    ],
    correct: 2,
    explanation: "The documented {{$userId}} scope resolves an end-user identity from the x-memory-user-id header or the caller's Entra identity. A static agent or project scope would intentionally share memory across users.",
    source: sources.memory,
  }),
  single({
    id: 168,
    domain,
    objective: "Choose conversation state rather than durable memory",
    difficulty: "Intermediate",
    skillId: "genai.agents",
    topicTags: ["conversation", "memory", "state"],
    variantGroup: "conversation-versus-durable-memory",
    stem: "An assistant must remember an order number during one support conversation, but policy forbids retaining it after that conversation ends. What should the design use?",
    options: [
      "A shared memory store with a permanent static scope",
      "Conversation state associated with that support session",
      "A file-search vector store containing every conversation transcript",
      "A system message containing the latest order number for every user",
    ],
    correct: 1,
    explanation: "Conversation state preserves context within the active interaction without turning transient identifiers into durable cross-session memory. File search and a shared system message would create inappropriate persistence or disclosure.",
    source: sources.memory,
  }),
  single({
    id: 169,
    domain,
    objective: "Choose file search for user-provided document grounding",
    difficulty: "Intermediate",
    skillId: "genai.rag",
    topicTags: ["file-search", "vector-store", "grounding"],
    variantGroup: "file-search-versus-conversation-memory",
    stem: "Users upload supported manuals and expect an agent to answer from their contents with citations. The files are not part of an existing enterprise search index. Which tool is the most direct fit?",
    options: [
      "Conversation memory, because it automatically indexes uploaded binary documents",
      "The file search tool backed by an attached vector store",
      "A reflection loop that asks the model to recall the manual",
      "A content filter configured as the agent's knowledge source",
    ],
    correct: 1,
    explanation: "File search uploads and indexes supported documents in a vector store that can be attached to the agent. Memory stores user-level learned information; they are not a substitute for document ingestion and retrieval.",
    source: sources.fileSearch,
  }),
  single({
    id: 170,
    domain,
    objective: "Require a configured retrieval tool for a response",
    difficulty: "Advanced",
    skillId: "genai.tools",
    topicTags: ["tool-choice", "file-search", "citations"],
    variantGroup: "file-search-tool-choice-required",
    stem: "A diagnostic request must use the agent's configured file-search tool, but responses sometimes answer from model knowledge and omit citations. Which response setting directly addresses this behavior?",
    options: [
      "Set tool_choice to required for the response",
      "Raise temperature so the model explores more documents",
      "Remove the vector store and place filenames in the system message",
      "Set max output tokens to the number of indexed files",
    ],
    correct: 0,
    explanation: "For the documented file-search scenario, tool_choice='required' forces tool use for that response. It does not guarantee relevant evidence exists, so vector-store attachment and indexing must still be verified.",
    source: sources.fileSearch,
  }),
  single({
    id: 171,
    domain,
    objective: "Expose unambiguous OpenAPI operations to an agent",
    difficulty: "Advanced",
    skillId: "genai.tools",
    topicTags: ["openapi", "operation-id", "tool-schema"],
    variantGroup: "openapi-unique-operation-id",
    stem: "An OpenAPI tool exposes two operations with the same operationId and overlapping descriptions. What should be corrected first?",
    options: [
      "Give every operation the same shorter description",
      "Make each operationId unique and keep each schema and description specific",
      "Remove authentication so the model can retry either operation",
      "Convert every request property to an unconstrained string",
    ],
    correct: 1,
    explanation: "The agent uses operation metadata to select and call tools. Unique operation IDs plus precise descriptions and bounded schemas reduce ambiguity; removing authentication or constraints makes the integration less safe.",
    source: sources.openApi,
  }),
  single({
    id: 172,
    domain,
    objective: "Choose a sequential workflow for ordered processing",
    difficulty: "Intermediate",
    skillId: "genai.tools",
    topicTags: ["workflow", "sequential", "orchestration"],
    variantGroup: "workflow-sequential-selection",
    lifecycle: "preview",
    stem: "A request must always pass through extraction, validation, and then summary, with each node consuming the previous node's saved output. Which workflow pattern is the clearest fit?",
    options: [
      "Sequential workflow",
      "Group chat with unrestricted dynamic handoff",
      "Independent parallel agents with no aggregation node",
      "A shared memory store used as an execution engine",
    ],
    correct: 0,
    explanation: "A sequential workflow explicitly preserves the required processing order and passes outputs between nodes. Dynamic group chat or uncoordinated parallel work would not guarantee extraction before validation and summary.",
    source: sources.workflows,
  }),
  single({
    id: 173,
    domain,
    objective: "Reference a local workflow variable in Power Fx",
    difficulty: "Advanced",
    skillId: "genai.tools",
    topicTags: ["power-fx", "workflow-variable", "scope"],
    variantGroup: "power-fx-local-variable-scope",
    lifecycle: "preview",
    stem: "A Foundry workflow saved a user response as a local variable named Var01. Which expression returns its uppercase value?",
    options: [
      "Upper(System.Var01)",
      "Upper(Local.Var01)",
      "ToUpper(Conversation.Var01)",
      "Upper(Var01.Value.Text)",
    ],
    correct: 1,
    explanation: "Foundry workflow Power Fx expressions prefix local variables with Local., and Upper transforms a string to uppercase. System. is reserved for documented system variables rather than saved local values.",
    source: sources.workflows,
  }),
  single({
    id: 174,
    domain,
    objective: "Place approval before a consequential tool call",
    difficulty: "Advanced",
    skillId: "genai.tools",
    topicTags: ["human-in-the-loop", "approval", "state-change"],
    variantGroup: "approval-before-tool-execution",
    stem: "A workflow drafts a payment request and a human must approve it. Where should the approval occur?",
    options: [
      "After the payment tool succeeds, so the reviewer sees the final transaction ID",
      "Before the payment tool, with the exact target and arguments shown to the reviewer",
      "Inside the model's hidden reasoning, with no separate approval event",
      "Once when the agent version is created, covering all future payments",
    ],
    correct: 1,
    explanation: "Approval must gate the consequential operation and cover the exact action and arguments that will execute. Post-action notification, hidden model reasoning, or blanket version approval cannot prevent an unwanted transaction.",
    source: sources.workflows,
    lifecycle: "preview",
  }),
  single({
    id: 175,
    domain,
    objective: "Use explicit handoff criteria in a multi-agent design",
    difficulty: "Advanced",
    skillId: "genai.agents",
    topicTags: ["multi-agent", "handoff", "routing"],
    variantGroup: "multi-agent-explicit-handoff",
    stem: "A triage agent can delegate to billing or technical specialists. Which design makes the handoff most testable?",
    options: [
      "Give all agents identical broad instructions and let them compete to answer",
      "Define specialist responsibilities, handoff criteria, and structured context passed at transfer",
      "Share one unrestricted tool credential and omit agent identities from traces",
      "Store routing decisions only in the final natural-language response",
    ],
    correct: 1,
    explanation: "Explicit roles, routing criteria, and structured transfer context make delegation observable and evaluable. Identical roles and hidden routing decisions create ambiguous ownership and make failures difficult to reproduce.",
    source: sources.agentRuntime,
  }),
  single({
    id: 176,
    domain,
    objective: "Evaluate tool argument accuracy separately from final response quality",
    difficulty: "Advanced",
    skillId: "genai.evaluation",
    topicTags: ["agent-evaluation", "tool-arguments", "process-quality"],
    variantGroup: "tool-input-accuracy-evaluator",
    stem: "An agent's final message sounds correct, but production incidents show malformed tool arguments. What should the evaluation emphasize?",
    options: [
      "Only fluency of the final response",
      "Tool input accuracy and task-adherence evidence from the agent trajectory",
      "Only model token count, because malformed arguments always use more tokens",
      "Only retrieval recall, even when no retrieval tool is involved",
    ],
    correct: 1,
    explanation: "Agent evaluation should inspect the process as well as the final answer. Tool-input accuracy checks whether required parameters, types, formats, and values are appropriate, while task adherence checks behavioral alignment.",
    source: sources.continuousEvaluation,
  }),
  multi({
    id: 177,
    domain,
    objective: "Protect per-user durable memory",
    difficulty: "Advanced",
    skillId: "genai.agents",
    topicTags: ["memory", "privacy", "retention"],
    variantGroup: "memory-privacy-controls",
    stem: "Which two practices are recommended when an agent stores durable user memory?",
    options: [
      "Use one shared static scope so recommendations improve across customers",
      "Map the memory scope to the end user and enforce per-user access controls",
      "Retain every interaction indefinitely so deletion cannot affect model quality",
      "Expose appropriate memory inspection and deletion controls and minimize sensitive content",
    ],
    correct: [1, 3],
    explanation: "Memory should be isolated by user, minimized, protected, and governed with retention and deletion controls. A shared scope or indefinite retention creates avoidable privacy and cross-user disclosure risks.",
    source: sources.memory,
  }),
  multi({
    id: 178,
    domain,
    objective: "Design a safe OpenAPI tool contract",
    difficulty: "Advanced",
    skillId: "genai.tools",
    topicTags: ["openapi", "schema", "authentication"],
    variantGroup: "safe-openapi-contract",
    stem: "Which two changes make an OpenAPI tool safer and easier for an agent to call correctly?",
    options: [
      "Use unique operation IDs with precise operation descriptions",
      "Allow undeclared request properties so the model can improvise",
      "Use bounded request schemas with required fields and appropriate authentication",
      "Put reusable API secrets in operation descriptions",
    ],
    correct: [0, 2],
    explanation: "Unique, descriptive operations and bounded authenticated schemas reduce ambiguity and constrain accepted actions. Undeclared arguments and secrets in descriptions expand the attack surface and weaken validation.",
    source: sources.openApi,
  }),
  {
    id: 179,
    section: "general",
    domain,
    objective: "Configure per-user agent memory in Python",
    difficulty: "Advanced",
    type: "code",
    language: "python",
    skillId: "genai.agents",
    topicTags: ["memory-search-tool", "scope", "python"],
    variantGroup: "memory-search-tool-python",
    lastVerified: "2026-09-01",
    lifecycle: "preview",
    stem: "Complete the memory tool so the service resolves a separate memory scope for each end user.",
    code: `from azure.ai.projects.models import MemorySearchPreviewTool

memory_tool = MemorySearchPreviewTool(
    memory_store_name=memory_store_name,
    scope={{memory_scope}},
    update_delay={{update_delay}},
)`,
    blanks: [
      { id: "memory_scope", label: "Per-user scope", options: [
        { id: "project", text: "\"project-shared\"" },
        { id: "user", text: "\"{{$userId}}\"" },
        { id: "agent", text: "agent_name" },
      ] },
      { id: "update_delay", label: "Production inactivity delay in seconds", options: [
        { id: "zero", text: "0" },
        { id: "five_minutes", text: "300" },
        { id: "negative", text: "-1" },
      ] },
    ],
    correct: { memory_scope: "user", update_delay: "five_minutes" },
    explanation: "The {{$userId}} placeholder enables per-user isolation when the request supplies the appropriate identity. The documented default-style production delay is five minutes; tiny test delays cause excessive memory updates.",
    source: sources.memory,
  },
  {
    id: 180,
    section: "general",
    domain,
    objective: "Attach a vector store to the file search tool",
    difficulty: "Advanced",
    type: "code",
    language: "json",
    skillId: "genai.rag",
    topicTags: ["file-search", "vector-store", "tool-resources"],
    variantGroup: "file-search-vector-store-json",
    lastVerified: "2026-09-01",
    stem: "Complete the agent configuration so file search can retrieve from the prepared vector store.",
    code: `{
  "tools": [
    { "type": "{{tool_type}}" }
  ],
  "tool_resources": {
    "file_search": {
      "vector_store_ids": ["{{vector_store_id}}"]
    }
  }
}`,
    blanks: [
      { id: "tool_type", label: "Tool type", options: [
        { id: "memory", text: "memory_search" },
        { id: "file", text: "file_search" },
        { id: "web", text: "web_search" },
      ] },
      { id: "vector_store_id", label: "Attached store identifier", options: [
        { id: "file_id", text: "file_abc123" },
        { id: "store_id", text: "vs_abc123" },
        { id: "conversation_id", text: "conv_abc123" },
      ] },
    ],
    correct: { tool_type: "file", vector_store_id: "store_id" },
    explanation: "The agent must declare the file_search tool and attach a vector-store ID through its file-search resources. A file ID or conversation ID does not identify the indexed retrieval collection.",
    source: sources.fileSearch,
  },
  {
    id: 181,
    section: "general",
    domain,
    objective: "Force configured tool use for a diagnostic response",
    difficulty: "Advanced",
    type: "code",
    language: "python",
    skillId: "genai.tools",
    topicTags: ["responses-api", "tool-choice", "file-search"],
    variantGroup: "responses-required-tool-choice",
    lastVerified: "2026-09-01",
    stem: "Complete the response call so at least one configured tool must be used for this diagnostic request.",
    code: `response = openai_client.responses.create(
    model=model_deployment,
    input="Find the documented reset procedure and cite it.",
    tools=tools,
    tool_choice={{tool_choice}},
)`,
    blanks: [
      { id: "tool_choice", label: "Tool-use requirement", options: [
        { id: "auto", text: "\"auto\"" },
        { id: "none", text: "\"none\"" },
        { id: "required", text: "\"required\"" },
      ] },
    ],
    correct: { tool_choice: "required" },
    explanation: "The required setting prevents the response from completing without a configured tool call. Auto permits the model to answer without retrieval, while none explicitly disables tool use.",
    source: sources.fileSearch,
  },
  {
    id: 182,
    section: "general",
    domain,
    objective: "Match agent state requirements to the correct mechanism",
    difficulty: "Intermediate",
    type: "matrix",
    skillId: "genai.agents",
    topicTags: ["conversation", "memory", "file-search"],
    variantGroup: "agent-state-mechanism-matrix",
    lastVerified: "2026-09-01",
    stem: "For each requirement, select the most appropriate agent mechanism.",
    rows: [
      { id: "turns", text: "Preserve context only across turns in the current support session" },
      { id: "preference", text: "Remember a user's durable communication preference across sessions" },
      { id: "manual", text: "Ground an answer in a newly uploaded product manual" },
    ],
    columns: [
      { id: "conversation", text: "Conversation state" },
      { id: "memory", text: "Per-user memory store" },
      { id: "file", text: "File search with an attached vector store" },
    ],
    correct: { turns: "conversation", preference: "memory", manual: "file" },
    explanation: "Conversation state is session-scoped, a per-user memory store supports durable learned preferences, and file search provides retrieval over uploaded documents. Treating these as interchangeable creates retention or grounding errors.",
    source: sources.memory,
  },
];
