import type { Question } from "../../questions";
import { multi, single } from "../builders";
import { expansionSources as sources } from "../sources";

const domain = "Plan and manage an Azure AI solution" as const;

export const planQuestions: Question[] = [
  single({
    id: 154,
    domain,
    objective: "Choose continuous evaluation for sampled production traffic",
    difficulty: "Advanced",
    skillId: "plan.observability",
    topicTags: ["continuous-evaluation", "production-monitoring", "sampling"],
    variantGroup: "evaluation-production-sampling",
    stem: "An agent passed its preproduction evaluation, but the team now needs quality and safety scores for a configurable sample of real production interactions. What should the team configure?",
    options: [
      "A larger local test dataset that is run manually after each incident",
      "Continuous evaluation for the deployed agent and its production traffic",
      "Distributed tracing with every span treated as an evaluation score",
      "A scheduled red-team scan with production sampling disabled",
    ],
    correct: 1,
    explanation: "Continuous evaluation samples deployed interactions and applies configured evaluators so quality and safety can be monitored over time. Traces provide diagnostic evidence, but a trace alone is not an evaluation score.",
    source: sources.continuousEvaluation,
  }),
  single({
    id: 155,
    domain,
    objective: "Grant the project identity only the role required for monitoring",
    difficulty: "Advanced",
    skillId: "plan.security",
    topicTags: ["rbac", "managed-identity", "continuous-evaluation"],
    variantGroup: "continuous-evaluation-project-identity",
    stem: "Continuous evaluation rules fail with authorization errors even though an engineer can view the project. Which identity should receive the documented project role required to run the rules?",
    options: [
      "Every engineer's personal identity at subscription scope",
      "The model deployment's service principal at tenant scope",
      "The Foundry project's managed identity at the project or required resource scope",
      "The browser session identity stored as a project connection secret",
    ],
    correct: 2,
    explanation: "Continuous evaluation uses the project managed identity to perform its work. Grant that workload identity the documented Foundry project role at the narrowest required scope instead of widening human or tenant permissions.",
    source: sources.agentDashboard,
  }),
  single({
    id: 156,
    domain,
    objective: "Govern preview capabilities through explicit lifecycle metadata",
    difficulty: "Intermediate",
    skillId: "plan.observability",
    topicTags: ["preview", "lifecycle", "release-governance"],
    variantGroup: "preview-feature-release-gate",
    stem: "A workflow capability is documented as preview. The application must meet a production SLA. What is the most appropriate release decision?",
    options: [
      "Treat preview and generally available features as equivalent when both appear in the portal",
      "Record the preview status, validate limitations, and require an explicit risk decision before production use",
      "Remove all evaluation because preview features cannot be measured",
      "Copy the preview API schema into the application so future service changes cannot affect it",
    ],
    correct: 1,
    explanation: "Preview status is a lifecycle and support constraint. It should be captured with the design, validated against requirements, and accepted explicitly rather than being inferred from portal availability or hidden by copied schemas.",
    source: sources.workflows,
    lifecycle: "preview",
  }),
  single({
    id: 157,
    domain,
    objective: "Select capacity from measured workload characteristics",
    difficulty: "Intermediate",
    skillId: "plan.deployment",
    topicTags: ["capacity", "throughput", "latency"],
    variantGroup: "capacity-bursty-versus-steady",
    stem: "A new application has bursty and unpredictable traffic, and the team has not yet established a sustained throughput baseline. Which initial deployment approach is most defensible?",
    options: [
      "Reserve the maximum provisioned capacity immediately and disable usage monitoring",
      "Use pay-per-use capacity with quota, throttling, latency, and token monitoring",
      "Create one deployment per user so each request has dedicated throughput",
      "Route overflow to an unapproved geography without checking data-residency requirements",
    ],
    correct: 1,
    explanation: "A consumption-style deployment plus measurement fits an uncertain bursty workload. Provisioned capacity becomes easier to justify after sustained demand and latency requirements are known and geographic constraints are satisfied.",
    source: sources.provisionedThroughput,
  }),
  single({
    id: 158,
    domain,
    objective: "Complete private endpoint connectivity with private DNS",
    difficulty: "Advanced",
    skillId: "plan.security",
    topicTags: ["private-endpoint", "dns", "network-isolation"],
    variantGroup: "private-endpoint-name-resolution",
    stem: "An application subnet can route to a Foundry private endpoint, but the service hostname still resolves to its public address. What is missing?",
    options: [
      "A larger model quota in the private endpoint region",
      "Private DNS configuration linked to the virtual network",
      "An API key stored in the subnet's route table",
      "A semantic ranker attached to the Foundry project",
    ],
    correct: 1,
    explanation: "Private endpoint traffic depends on name resolution mapping the service hostname to the endpoint's private address. Routing alone does not rewrite DNS, and credentials or model quota cannot correct the resolved destination.",
    source: sources.foundryAuth,
  }),
  single({
    id: 159,
    domain,
    objective: "Distinguish diagnostic tracing from quality evaluation",
    difficulty: "Intermediate",
    skillId: "plan.observability",
    topicTags: ["tracing", "evaluation", "root-cause-analysis"],
    variantGroup: "tracing-versus-evaluation",
    stem: "A groundedness score drops after a release. Which combination best supports both detection and root-cause analysis?",
    options: [
      "Continuous evaluation to detect the score change and correlated traces to inspect retrieval and tool spans",
      "Token-count alerts to detect the score change and model temperature to identify the failing document",
      "Search replicas to calculate groundedness and quota metrics to reconstruct prompts",
      "A content filter to calculate relevance and a deployment name to reconstruct tool arguments",
    ],
    correct: 0,
    explanation: "Evaluation measures response qualities such as groundedness, while correlated traces expose the retrieval, model, and tool operations that produced an interaction. The two signals answer different but complementary questions.",
    source: sources.continuousEvaluation,
  }),
  multi({
    id: 160,
    domain,
    objective: "Retain provenance needed to reproduce a generated asset",
    difficulty: "Advanced",
    skillId: "plan.observability",
    topicTags: ["provenance", "audit", "model-version"],
    variantGroup: "generated-asset-provenance",
    stem: "Which two records are most important for reproducing and auditing an approved generated asset?",
    options: [
      "The exact model deployment or version and generation parameters",
      "The source-asset identifiers, prompt, and approval decision",
      "Only the final file size and the reviewer's display name",
      "Only the current model catalog entry, even if the asset used an older deployment",
    ],
    correct: [0, 1],
    explanation: "Reproducible provenance connects the output to its exact model/deployment, inputs, parameters, source assets, safety results, and approval. Current catalog metadata or superficial file properties cannot reconstruct an earlier generation.",
    source: sources.tracing,
  }),
  multi({
    id: 161,
    domain,
    objective: "Apply least privilege to state-changing agent tools",
    difficulty: "Advanced",
    skillId: "plan.security",
    topicTags: ["least-privilege", "tool-governance", "human-approval"],
    variantGroup: "state-changing-tool-controls",
    stem: "An agent can read inventory and submit purchase orders. Which two controls most directly reduce the impact of an erroneous tool call?",
    options: [
      "Give the agent a narrow order schema and credentials limited to the required operations",
      "Require approval before the state-changing submission while allowing read-only lookup without that approval",
      "Give every agent Contributor so a failed call can repair its own permissions",
      "Place the purchase-order API key in the system prompt so the model can verify it",
    ],
    correct: [0, 1],
    explanation: "A narrow schema and least-privilege credential bound what the tool can do, while approval gates the consequential action. Broad roles and secrets in prompts increase both accidental and adversarial impact.",
    source: sources.openApi,
  }),
  {
    id: 162,
    section: "general",
    domain,
    objective: "Configure keyless authentication for a Foundry project client",
    difficulty: "Intermediate",
    type: "code",
    language: "python",
    skillId: "plan.security",
    topicTags: ["default-azure-credential", "project-client", "keyless-auth"],
    variantGroup: "project-client-keyless-auth",
    lastVerified: "2026-09-01",
    stem: "Complete the client initialization so the same code can use a developer identity locally and a managed identity in Azure.",
    code: `from azure.ai.projects import AIProjectClient
from azure.identity import {{credential_import}}

credential = {{credential_class}}()
project = AIProjectClient(
    endpoint=os.environ["AZURE_AI_PROJECT_ENDPOINT"],
    credential=credential,
)`,
    blanks: [
      { id: "credential_import", label: "Credential import", options: [
        { id: "default_import", text: "DefaultAzureCredential" },
        { id: "key_import", text: "AzureKeyCredential" },
        { id: "token_import", text: "AccessToken" },
      ] },
      { id: "credential_class", label: "Credential instance", options: [
        { id: "default", text: "DefaultAzureCredential" },
        { id: "interactive", text: "InteractiveBrowserCredential" },
        { id: "key", text: "AzureKeyCredential" },
      ] },
    ],
    correct: { credential_import: "default_import", credential_class: "default" },
    explanation: "DefaultAzureCredential follows a credential chain that supports local developer authentication and managed identity in Azure. AzureKeyCredential would require storing and rotating a service key.",
    source: sources.foundryAuth,
  },
  {
    id: 163,
    section: "general",
    domain,
    objective: "Assign a Foundry project role at a narrow scope",
    difficulty: "Advanced",
    type: "code",
    language: "azurecli",
    skillId: "plan.security",
    topicTags: ["rbac", "managed-identity", "scope"],
    variantGroup: "foundry-role-assignment-cli",
    lastVerified: "2026-09-01",
    stem: "Complete the role assignment for a workload identity without granting subscription-wide control.",
    code: `az role assignment create \
  --assignee-object-id $WORKLOAD_OBJECT_ID \
  --assignee-principal-type {{principal_type}} \
  --role "{{role_name}}" \
  --scope $FOUNDRY_PROJECT_SCOPE`,
    blanks: [
      { id: "principal_type", label: "Managed identity principal type", options: [
        { id: "service_principal", text: "ServicePrincipal" },
        { id: "user", text: "User" },
        { id: "group", text: "Group" },
      ] },
      { id: "role_name", label: "Project data-plane role", options: [
        { id: "foundry_user", text: "Foundry User" },
        { id: "owner", text: "Owner" },
        { id: "reader", text: "Reader" },
      ] },
    ],
    correct: { principal_type: "service_principal", role_name: "foundry_user" },
    explanation: "A managed identity is represented by a service principal. Foundry User supplies project data-plane capabilities without the broad resource-management authority of Owner, and the project scope limits the assignment.",
    source: sources.foundryRbac,
  },
  {
    id: 164,
    section: "general",
    domain,
    objective: "Constrain a strict tool schema",
    difficulty: "Advanced",
    type: "code",
    language: "json",
    skillId: "plan.security",
    topicTags: ["tool-schema", "strict-validation", "least-privilege"],
    variantGroup: "strict-state-change-schema",
    lastVerified: "2026-09-01",
    stem: "Complete the JSON Schema so the state-changing tool accepts only the two reviewed arguments.",
    code: `{
  "type": "object",
  "properties": {
    "orderId": { "type": "string" },
    "approvedAmount": { "type": "number", "minimum": 0 }
  },
  "required": ["orderId", "approvedAmount"],
  "additionalProperties": {{additional_properties}}
}`,
    blanks: [
      { id: "additional_properties", label: "Unexpected argument policy", options: [
        { id: "deny", text: "false" },
        { id: "allow", text: "true" },
        { id: "null", text: "null" },
      ] },
    ],
    correct: { additional_properties: "deny" },
    explanation: "Setting additionalProperties to false rejects undeclared arguments. Combined with explicit required fields and constraints, this reduces the tool's accepted input surface and makes validation deterministic.",
    source: sources.openApi,
  },
  {
    id: 165,
    section: "general",
    domain,
    objective: "Order the release and monitoring lifecycle",
    difficulty: "Intermediate",
    type: "order",
    skillId: "plan.observability",
    topicTags: ["evaluation", "release-gate", "continuous-monitoring"],
    variantGroup: "evaluation-release-lifecycle",
    lastVerified: "2026-09-01",
    stem: "Arrange the activities in the most defensible order for releasing a changed agent.",
    options: [
      { id: "dataset", text: "Build or update a representative labeled evaluation dataset" },
      { id: "evaluate", text: "Run quality, safety, and tool-behavior evaluations against the candidate" },
      { id: "gate", text: "Compare results with thresholds and approve or reject the candidate" },
      { id: "monitor", text: "Deploy the approved version and continuously evaluate sampled production traffic" },
    ],
    correct: ["dataset", "evaluate", "gate", "monitor"],
    explanation: "A representative dataset precedes evaluation, evaluation evidence informs the release gate, and production monitoring begins only after the approved candidate is deployed. Reversing the order turns production users into the test set.",
    source: sources.continuousEvaluation,
  },
  {
    id: 166,
    section: "general",
    domain,
    objective: "Match operational questions to the correct evidence",
    difficulty: "Advanced",
    type: "match",
    skillId: "plan.observability",
    topicTags: ["metrics", "traces", "evaluation", "audit"],
    variantGroup: "observability-evidence-types",
    lastVerified: "2026-09-01",
    stem: "Match each operational question to the evidence that most directly answers it.",
    prompts: [
      { id: "quality", text: "Did groundedness degrade for sampled production answers?" },
      { id: "latency", text: "Which retrieval or tool span caused the latency increase?" },
      { id: "approval", text: "Who approved the state-changing action and with which arguments?" },
    ],
    choices: [
      { id: "evaluation", text: "Continuous evaluation results" },
      { id: "trace", text: "Correlated distributed traces" },
      { id: "audit", text: "Immutable approval and provenance record" },
      { id: "quota", text: "Subscription quota allocation" },
    ],
    correct: { quality: "evaluation", latency: "trace", approval: "audit" },
    explanation: "Evaluation scores describe response quality, traces locate latency within an interaction, and approval records establish accountability for consequential actions. Quota data cannot substitute for any of those records.",
    source: sources.continuousEvaluation,
  },
];
