import type { Question } from "../../questions";
import { multi, single } from "../builders";
import { expansionSources as sources } from "../sources";

const domain = "Implement text analysis solutions" as const;

export const textQuestions: Question[] = [
  single({
    id: 190,
    domain,
    objective: "Mitigate mixed-language input limitations in Translator",
    difficulty: "Advanced",
    skillId: "text.translation",
    topicTags: ["translator", "mixed-language", "segmentation"],
    variantGroup: "translator-mixed-language-segments",
    stem: "A single customer message alternates between French and German phrases. Translator returns incomplete English output. What is the documented mitigation?",
    options: [
      "Submit the entire message without a source language and increase max tokens",
      "Split the input into single-language segments and translate each with its intended source language",
      "Transliterate the message before every translation request",
      "Use document OCR because OCR automatically resolves mixed-language sentences",
    ],
    correct: 1,
    explanation: "Translator does not reliably support sentences containing mixed-language text. Segmenting the content into single-language units and specifying the intended source language avoids asking one request to interpret conflicting language context.",
    source: sources.translatorIssues,
  }),
  single({
    id: 191,
    domain,
    objective: "Handle an expired Custom Speech model correctly",
    difficulty: "Advanced",
    skillId: "text.speech",
    topicTags: ["custom-speech", "model-lifecycle", "fallback"],
    variantGroup: "custom-speech-expired-model-routes",
    stem: "A Custom Speech model expires before the team updates its deployments. What behavior should operations expect?",
    options: [
      "Both custom endpoints and batch transcription silently use any model in any locale",
      "The custom endpoint falls back to the newest base model for the same locale, while a batch request that names the expired model fails with a 4xx error",
      "The custom endpoint returns a 2xx response with no transcript, while batch transcription retrains the model automatically",
      "Both routes continue using the expired custom model indefinitely because it was previously deployed",
    ],
    correct: 1,
    explanation: "The documented behaviors differ: a custom endpoint falls back to the newest base model for its locale, potentially reducing domain accuracy, while batch transcription requests that reference an expired model fail with a client error.",
    source: sources.customSpeechLifecycle,
  }),
  single({
    id: 192,
    domain,
    objective: "Use PII detection to redact sensitive text",
    difficulty: "Intermediate",
    skillId: "text.language",
    topicTags: ["pii", "redaction", "azure-language"],
    variantGroup: "pii-redacted-text-output",
    stem: "A support application must locate personal identifiers in free text and produce a version suitable for downstream diagnostics with those entities obscured. Which capability should it use?",
    options: [
      "Azure Language PII detection and its redacted text output",
      "Translator transliteration with the target script set to Latin",
      "Speech synthesis with word-boundary events",
      "Semantic ranking with captions disabled",
    ],
    correct: 0,
    explanation: "Azure Language PII detection identifies supported personal-information categories and can return redacted text. Translation, synthesis, and semantic ranking do not provide entity-level PII recognition and redaction.",
    source: sources.pii,
  }),
  multi({
    id: 193,
    domain,
    objective: "Design a privacy-aware PII processing path",
    difficulty: "Advanced",
    skillId: "text.language",
    topicTags: ["pii", "logging", "human-review"],
    variantGroup: "pii-processing-controls",
    stem: "Which two practices best reduce accidental disclosure when processing support transcripts for diagnostics?",
    options: [
      "Write the original transcript to every trace before running detection",
      "Run PII detection before placing transcript content in ordinary diagnostic logs",
      "Retain entity category and position information only where the diagnostic workflow actually requires it",
      "Assume redaction is unnecessary when the transcript was produced by Speech rather than typed by a user",
    ],
    correct: [1, 2],
    explanation: "PII controls should occur before broad diagnostic propagation, and retained sensitive metadata should be minimized to the workflow's needs. Speech-derived text can contain the same personal information as typed text.",
    source: sources.pii,
  }),
  {
    id: 194,
    section: "general",
    domain,
    objective: "Redact detected PII with the Python SDK",
    difficulty: "Intermediate",
    type: "code",
    language: "python",
    skillId: "text.language",
    topicTags: ["pii", "python-sdk", "redacted-text"],
    variantGroup: "pii-python-redaction",
    lastVerified: "2026-09-01",
    stem: "Complete the code that detects PII in one message and returns the service-produced redacted text.",
    code: `result = client.{{operation}}(
    documents=[message],
    language="en",
)[0]

safe_for_diagnostics = result.{{output_field}}`,
    blanks: [
      { id: "operation", label: "Language operation", options: [
        { id: "sentiment", text: "analyze_sentiment" },
        { id: "pii", text: "recognize_pii_entities" },
        { id: "keyphrases", text: "extract_key_phrases" },
      ] },
      { id: "output_field", label: "Redacted output", options: [
        { id: "entities", text: "entities" },
        { id: "redacted", text: "redacted_text" },
        { id: "warnings", text: "warnings" },
      ] },
    ],
    correct: { operation: "pii", output_field: "redacted" },
    explanation: "recognize_pii_entities runs the PII operation, and redacted_text contains the service-generated text with recognized entities obscured. The entities collection instead contains detailed detections and offsets.",
    source: sources.pii,
  },
  {
    id: 195,
    section: "general",
    domain,
    objective: "Translate one language-homogeneous segment with REST",
    difficulty: "Advanced",
    type: "code",
    language: "http",
    skillId: "text.translation",
    topicTags: ["translator", "rest", "source-language"],
    variantGroup: "translator-segment-rest-request",
    lastVerified: "2026-09-01",
    stem: "The application has isolated a French segment from a mixed-language message. Complete the request that translates only this segment to English.",
    code: `POST https://api.cognitive.microsofttranslator.com/{{operation}}?api-version=3.0&from={{source_language}}&to=en
Ocp-Apim-Subscription-Key: {translator-key}
Content-Type: application/json

[{ "Text": "La pompe est arrêtée." }]`,
    blanks: [
      { id: "operation", label: "Translator operation", options: [
        { id: "detect", text: "detect" },
        { id: "translate", text: "translate" },
        { id: "transliterate", text: "transliterate" },
      ] },
      { id: "source_language", label: "Known segment language", options: [
        { id: "auto", text: "auto" },
        { id: "de", text: "de" },
        { id: "fr", text: "fr" },
      ] },
    ],
    correct: { operation: "translate", source_language: "fr" },
    explanation: "The translate operation converts the isolated segment, and from=fr supplies its known source language. Segmentation prevents the request from containing multiple languages that the service does not reliably handle as one sentence.",
    source: sources.translatorIssues,
  },
  {
    id: 196,
    section: "general",
    domain,
    objective: "Order a mixed-language translation pipeline",
    difficulty: "Advanced",
    type: "order",
    skillId: "text.translation",
    topicTags: ["translator", "segmentation", "quality-review"],
    variantGroup: "mixed-language-translation-order",
    lastVerified: "2026-09-01",
    stem: "Arrange the processing stages for a message that contains several language-homogeneous segments.",
    options: [
      { id: "segment", text: "Separate the message into language-homogeneous segments" },
      { id: "identify", text: "Determine or validate the source language for each segment" },
      { id: "translate", text: "Translate each segment with its intended source and target language" },
      { id: "assemble", text: "Reassemble the outputs in order and apply any required human quality review" },
    ],
    correct: ["segment", "identify", "translate", "assemble"],
    explanation: "The mitigation begins by isolating single-language inputs, then associating each with the proper source language. Translation occurs per segment before ordered reconstruction and any review required by the scenario.",
    source: sources.translatorIssues,
  },
];
