import type { Question } from "../../questions";
import { multi, single } from "../builders";
import { expansionSources as sources } from "../sources";

const domain = "Implement computer vision solutions" as const;

export const visionQuestions: Question[] = [
  single({
    id: 183,
    domain,
    objective: "Ground visual answers in observable evidence",
    difficulty: "Intermediate",
    skillId: "vision.understanding",
    topicTags: ["visual-question-answering", "grounding", "uncertainty"],
    variantGroup: "visual-evidence-insufficient-image",
    stem: "A user asks whether a photographed control panel has a damaged connector, but the connector is outside the frame. How should a grounded multimodal assistant respond?",
    options: [
      "Infer the connector's condition from the visible warning light",
      "State that the connector is damaged because that is the safer assumption",
      "Explain that the image does not show the connector and request a suitable photograph",
      "Generate a likely connector image and analyze the generated pixels",
    ],
    correct: 2,
    explanation: "A visually grounded answer must distinguish observed evidence from missing information. Requesting another image is appropriate when the required region is absent; inference or generated imagery cannot establish the real connector's state.",
    source: sources.multimodal,
  }),
  single({
    id: 184,
    domain,
    objective: "Use a mask for a bounded image edit",
    difficulty: "Intermediate",
    skillId: "vision.generation",
    topicTags: ["image-editing", "mask", "inpainting"],
    variantGroup: "bounded-image-edit-mask",
    stem: "A designer must replace only the sky in an approved product photograph while preserving the product and foreground. What should the edit request include?",
    options: [
      "Only a text prompt describing the entire photograph from memory",
      "The source image and a compatible mask identifying the editable sky region",
      "A lower-quality copy with the product cropped out",
      "Two unrelated reference images and no source photograph",
    ],
    correct: 1,
    explanation: "A mask constrains an inpainting-style edit to the intended region while the source image provides the pixels that should be preserved. Prompt-only regeneration offers no equivalent boundary or source fidelity.",
    source: sources.imageGeneration,
  }),
  single({
    id: 185,
    domain,
    objective: "Decode base64 image-generation output",
    difficulty: "Advanced",
    skillId: "vision.generation",
    topicTags: ["image-generation", "base64", "output-handling"],
    variantGroup: "gpt-image-base64-output",
    stem: "An image-generation response contains b64_json rather than a public URL. What should the application do to persist the generated image?",
    options: [
      "Treat b64_json as a Blob Storage URL and issue an HTTP GET",
      "Base64-decode the value to bytes and write those bytes using the intended image format",
      "Send the value to Translator before storing it",
      "Store the encoded string directly in a .png file without decoding",
    ],
    correct: 1,
    explanation: "The b64_json field carries base64-encoded image bytes. The application must decode it before writing an image file; treating it as a URL or writing the text itself produces an invalid artifact.",
    source: sources.imageGeneration,
  }),
  multi({
    id: 186,
    domain,
    objective: "Generate accessible descriptions without inventing detail",
    difficulty: "Advanced",
    skillId: "vision.understanding",
    topicTags: ["alt-text", "accessibility", "visual-grounding"],
    variantGroup: "accessible-alt-text-controls",
    stem: "Which two instructions best support useful, evidence-grounded alt text?",
    options: [
      "Describe information needed to understand the image's purpose and context",
      "Infer product claims that are likely true even when they are not visible",
      "State uncertainty or omit details that cannot be verified from the image",
      "Always produce the longest possible description regardless of page context",
    ],
    correct: [0, 2],
    explanation: "Accessible descriptions should communicate relevant visible information and represent uncertainty honestly. Unsupported claims and mechanically long output can mislead users and obscure the image's actual purpose.",
    source: sources.multimodal,
  }),
  multi({
    id: 187,
    domain,
    objective: "Protect a multimodal workflow from harmful content and document attacks",
    difficulty: "Advanced",
    skillId: "vision.safety",
    topicTags: ["content-safety", "prompt-shields", "multimodal"],
    variantGroup: "multimodal-safety-layering",
    stem: "Partner images can contain unsafe imagery and printed instructions intended to manipulate the agent. Which two controls address these distinct risks?",
    options: [
      "Classify the image with the applicable content-safety controls",
      "Increase image resolution so hidden instructions become trustworthy",
      "Run Prompt Shields or equivalent document-attack detection on untrusted grounding content",
      "Let the vision model follow printed instructions before the system message",
    ],
    correct: [0, 2],
    explanation: "Content classification and indirect prompt-attack detection address different threat categories and should be layered. Better resolution does not establish trust, and untrusted text must never override system policy.",
    source: sources.promptShields,
  }),
  {
    id: 188,
    section: "general",
    domain,
    objective: "Decode an image-generation response in Python",
    difficulty: "Intermediate",
    type: "code",
    language: "python",
    skillId: "vision.generation",
    topicTags: ["image-generation", "python", "base64"],
    variantGroup: "image-output-decode-python",
    lastVerified: "2026-09-01",
    stem: "Complete the code that converts the encoded response into image bytes and saves them.",
    code: `import base64

encoded = result.data[0].{{response_field}}
image_bytes = base64.{{decode_method}}(encoded)

with open("campaign.png", "wb") as output:
    output.write(image_bytes)`,
    blanks: [
      { id: "response_field", label: "Encoded image field", options: [
        { id: "url", text: "url" },
        { id: "b64", text: "b64_json" },
        { id: "revised", text: "revised_prompt" },
      ] },
      { id: "decode_method", label: "Base64 conversion", options: [
        { id: "encode", text: "b64encode" },
        { id: "decode", text: "b64decode" },
        { id: "hex", text: "b16decode" },
      ] },
    ],
    correct: { response_field: "b64", decode_method: "decode" },
    explanation: "Current image-generation responses can return the image in b64_json. base64.b64decode converts that text representation into the binary bytes expected by an image file.",
    source: sources.imageGeneration,
  },
  {
    id: 189,
    section: "general",
    domain,
    objective: "Match visual workloads to the appropriate mechanism",
    difficulty: "Intermediate",
    type: "matrix",
    skillId: "vision.understanding",
    topicTags: ["multimodal", "image-editing", "content-safety"],
    variantGroup: "vision-workload-mechanism-matrix",
    lastVerified: "2026-09-01",
    stem: "For each requirement, select the most direct mechanism.",
    rows: [
      { id: "question", text: "Answer a question about relationships visible in a photograph" },
      { id: "edit", text: "Replace one bounded region while preserving the rest of the source image" },
      { id: "unsafe", text: "Classify whether visual content falls into configured harm categories" },
    ],
    columns: [
      { id: "multimodal", text: "Vision-enabled multimodal model" },
      { id: "mask", text: "Mask-based image edit" },
      { id: "safety", text: "Visual content-safety classification" },
    ],
    correct: { question: "multimodal", edit: "mask", unsafe: "safety" },
    explanation: "Multimodal reasoning handles contextual visual questions, a mask constrains a localized edit, and content-safety classification evaluates configured harm categories. Each mechanism solves a different visual task.",
    source: sources.multimodal,
  },
];
