export const distractorTextOverrides: Record<number, Record<string, string>> = {
  1: {
    c: "Use the managed identity but assign only control-plane Reader on the Foundry and Search resources",
    d: "Store both service keys in Key Vault and let the App Service retrieve them at startup",
  },
  2: {
    a: "Use vector-only retrieval, return source URLs, and rely on embeddings for exact policy identifiers",
    c: "Use keyword-only retrieval with semantic reranking and return document URLs with each result",
    d: "Use hybrid retrieval with semantic reranking but pass only excerpt text, without source identifiers, to the agent",
  },
  3: {
    a: "Execute the refund with an idempotency key, then require a supervisor to approve the completed transaction",
    c: "Pause only when the model reports low confidence; otherwise let the agent execute the refund directly",
    d: "Require a second agent to approve the first agent's recommendation before the refund tool executes",
  },
  4: {
    a: "Correlated trace spans for model, retrieval, and tool operations under one operation identifier",
    b: "Retrieved document and chunk identifiers retained as source-provenance metadata",
    c: "Approval request, reviewer decision, and resulting action events retained in the same trace",
    d: "Per-service request and error totals aggregated by hour without a shared operation identifier",
    e: "The final answer, total duration, and token count without retrieval, tool, or approval events",
  },
  5: {
    a: "A Foundry Agent Service conversation scoped to the current support session",
    b: "A chain linked only through previous_response_id values",
    c: "A vector store containing embeddings of all support messages",
    d: "A trace that records each request and response span",
  },
  6: {
    a: "Combine OCR text with a fixed caption template and omit non-text visual details",
    c: "Use an automatic image-caption capability without an accessibility instruction or evidence constraint",
    d: "Generate alt text from catalog metadata and use the image only to verify the product category",
  },
  7: {
    a: "A custom Content Understanding analyzer with a field schema, content output, and detailed grounding",
    b: "A Document Intelligence custom neural model trained on labeled campaign PDFs",
    c: "The Document Intelligence prebuilt layout model followed by application-written extraction rules",
    d: "An Azure AI Search skillset that runs OCR and maps the resulting text directly to the index",
  },
  8: {
    a: "Full-text keyword search to preserve exact product names, codes, and phrases",
    b: "Vector search over campaign content to retrieve conceptually similar material",
    c: "Semantic reranking applied to the merged keyword and vector result set",
    d: "A scoring profile that boosts recently modified documents after a keyword-only query",
    e: "Faceted navigation over product and campaign fields without semantic or vector retrieval",
  },
  9: {
    a: "Run the Content Safety Analyze Image API and trust all text when the image has low harm scores",
    c: "Use OCR to remove sentences containing imperative verbs before sending the remaining text to the model",
    d: "Add a system instruction that says image text is untrusted, without scanning retrieved or uploaded content",
  },
  10: {
    a: "Use public endpoints restricted by service firewalls and authenticate each workload with managed identity",
    c: "Use private endpoints and private DNS but authenticate every workload with one centrally rotated service key",
    d: "Use VNet integration for the application subnet while leaving each AI service on its public endpoint",
  },
  14: {
    a: "Retry every second for a fixed number of attempts without inspecting Retry-After",
    c: "Immediately route every throttled call to another deployment in the same quota pool",
    d: "Request more quota but leave the client without a bounded transient-failure policy",
  },
  15: {
    a: "Use a client secret stored in Key Vault and rotate it through the deployment pipeline",
    c: "Use the project's API key stored in Key Vault and retrieve it through the container's managed identity",
    d: "Use an interactive developer credential in production and restrict access through conditional access",
  },
  16: {
    a: "Prompt Shields for direct user-prompt attacks and indirect attacks in documents",
    b: "Analyze Text and Analyze Image APIs for harm-category severity classification",
    c: "Task adherence checks for agent tool calls that may be misaligned or premature",
    d: "Groundedness detection for comparing generated answers with supplied source material",
    e: "Protected-material detection for identifying known text or code in generated output",
  },
  17: {
    a: "The model name plus the exact deployment and workflow versions used for the run",
    b: "The tool name, server-validated arguments, result identifier, and execution status",
    c: "Retrieved document and chunk identifiers together with the effective search-index version",
    d: "Hourly aggregate latency, token, and error metrics without operation-level correlation",
    e: "The generated recommendation and model confidence without retrieved evidence or tool arguments",
  },
  18: {
    a: "Groundedness and answer-relevance measurements from a representative evaluation set",
    b: "Search-index freshness, ingestion health, and retrieval-quality measurements",
    c: "Safety-filter events and rates broken down by the applicable risk categories",
    d: "End-to-end and component latency, token consumption, retry, and throttling signals",
    e: "Only overall endpoint availability and request volume, without retrieval or model-quality telemetry",
  },
  19: {
    a: "Edit the production prompt in the portal, export it afterward, and compare a small sample manually",
    c: "Promote the newest model automatically, then run the representative evaluation set against production traffic",
    d: "Run the evaluation gate in test but allow operators to change the production prompt and index configuration manually",
  },
  20: {
    b: "A descriptive tool name with one unconstrained string argument containing all requested work",
    c: "A constrained schema whose values are checked only in the browser before being sent to the backend",
    d: "A clear schema that declares properties but omits required fields and allows undeclared arguments",
  },
  23: {
    b: "A fixed sequential workflow that invokes billing, technical, and compliance once in the same order",
    c: "A handoff workflow in which the active specialist transfers control and cannot rejoin the discussion",
    d: "A concurrent fan-out workflow that runs all specialists once and merges their independent answers",
  },
  24: {
    d: "Always retrieve only the single highest-scoring chunk, regardless of score distribution or evidence coverage",
    e: "Use the largest possible fixed chunks without overlap so fewer records are placed in the search index",
  },
  25: {
    b: "Use JSON mode with a high temperature and validate only that the result parses as JSON",
    c: "Use the required structured schema but increase temperature to maximize variation in extracted values",
    d: "Use a low temperature with prompt examples but accept any object shape the model returns",
  },
  26: {
    a: "Groundedness evaluation comparing answer claims with the supplied source passages",
    b: "Relevance evaluation measuring whether the answer addresses the user's question",
    c: "Safety evaluation covering harmful, disallowed, or policy-violating model behavior",
    d: "Coherence and fluency of the prose, without comparing claims to the supplied passages",
    e: "Median latency and token cost, without measuring whether the answer is useful or safe",
  },
  27: {
    b: "Collect only Application Insights request duration and failure metrics for the public HTTP endpoint",
    c: "Write separate model, Search, and tool logs without propagating a correlation context",
    d: "Create one trace span around the model call and record retrieval and tools only as unstructured text",
  },
  28: {
    b: "Route every request to a small model and retry failures with the same model using a longer prompt",
    c: "Route every request to the largest model and use caching as the only cost-control mechanism",
    d: "Route solely by prompt character count without evaluating intent complexity or result quality",
  },
  29: {
    b: "Continue drafting and critiquing until the critic assigns its own output a perfect score",
    c: "Run one critic pass without explicit criteria, then accept every revision the creator produces",
    d: "Give the critic publication tools so it can approve and publish any draft that passes self-critique",
  },
  30: {
    b: "The Foundry project endpoint and an AzureKeyCredential created from a project key in application settings",
    c: "An Azure OpenAI resource endpoint and DefaultAzureCredential, without the Foundry project path",
    d: "The Foundry project resource ID and a bearer token acquired once during application startup",
  },
  31: {
    b: "Link turns only through previous_response_id and retain every response chain after the session ends",
    c: "Store every user's message in one application-wide history and pass the complete history on each turn",
    d: "Put session messages into a shared vector store and retrieve the nearest messages for every user",
  },
  33: {
    a: "Route simple, evaluated request classes to a smaller model that meets their quality target",
    b: "Remove redundant instructions and retrieved passages while preserving required evidence",
    c: "Measure token consumption by feature and enforce explicit budgets, thresholds, or alerts",
    d: "Cache generated answers across users without partitioning the cache by identity or authorization context",
    e: "Truncate every prompt and retrieval result to one fixed size before evaluating whether required evidence is lost",
  },
  34: {
    b: "Use JSON mode, parse the object, and accept it whenever the JSON syntax is valid",
    c: "Show the model several JSON examples and retry whenever the returned property names differ",
    d: "Repair malformed or missing fields in application code without validating the repaired object against the contract",
  },
  35: {
    b: "Send the source image with high input fidelity but omit a mask and ask the model not to change other pixels",
    c: "Send the source image and mask to the image generations operation rather than the edits operation",
    d: "Send a same-sized mask that selects the product instead of the logo area and use the correct edit prompt",
  },
  37: {
    b: "Run OCR on the gauge labels and infer the needle position from the recognized threshold text",
    c: "Compare an image embedding with labeled high- and low-pressure examples and return the nearest label",
    d: "Use a custom object detector to locate the gauge, then assume any detected gauge is above threshold",
  },
  38: {
    b: "Use Azure AI Video Indexer and keep its standard transcript and insights without the required custom output schema",
    c: "Combine Speech transcription with periodic-frame OCR and merge the results without a shared segment timeline",
    d: "Send the entire video to a multimodal model for one summary and discard segment-level source locations",
  },
  40: {
    b: "Supply a plain-text utterance plus a pronunciation lexicon but no markup for the required pause",
    c: "Set speaking rate and pitch in the SDK request but leave the product pronunciation and pause unspecified",
    d: "Train a custom voice for the product name and insert punctuation where the warning pause should occur",
  },
  41: {
    b: "Stream speech to text, then send every finalized segment to Translator in a separate request",
    c: "Submit each buffered utterance to fast transcription and translate it after the synchronous result returns",
    d: "Upload completed calls for batch transcription and translate the batch output after the call ends",
  },
  42: {
    a: "Azure Translator Text in Foundry Tools, called directly for each already-extracted text segment",
    b: "Create temporary documents from the segments and submit each file to Document Translation",
    c: "Send every segment to a general language model with a translation instruction and no terminology controls",
    d: "Convert the segments to synthetic speech and use Speech Translation on the generated audio",
  },
  43: {
    a: "Named entities and topics extracted into the declared feedback-analysis structure",
    b: "A concise feedback summary constrained by the application's review instructions",
    c: "Structured JSON whose properties and types conform to a supplied output schema",
    d: "Word-level speaker timestamps for each feedback item",
    e: "Page-coordinate bounding polygons for every extracted phrase",
  },
  44: {
    b: "Use extractive summarization and add headings afterward without retrieving or preserving clause identifiers",
    c: "Use a structured prompt and examples but rely on model memory instead of retrieving the governing clauses",
    d: "Fine-tune a model on prior summaries and accept free-form output without a schema or citation validation",
  },
  47: {
    a: "Optical character recognition that recovers text from every scanned invoice page",
    b: "Layout and table analysis that preserves rows, columns, and spatial relationships",
    c: "Field extraction that maps invoice values and line items into a declared schema",
    d: "Language detection and key-phrase extraction before sending the original page text to the model",
    e: "Semantic reranking of previously extracted invoice text without OCR or layout-aware field extraction",
  },
  49: {
    a: "Markdown output that retains headings and simple table structure for downstream chunking",
    b: "Plain text with line breaks but without heading levels or table structure",
    c: "Only the extracted business-field JSON, without the readable document representation",
    d: "Page images and bounding boxes without a text representation suitable for chunking",
  },
  50: {
    d: "Give the agent broad tools and credentials but require human approval before every read and write call",
    e: "Use narrow tools but let the model treat a high confidence score as authorization for destructive calls",
  },
  51: {
    a: "Store the claims API key in a centrally managed project connection that is available to every claims agent",
    e: "Assign the application's managed identity Contributor on each production resource group to simplify access",
  },
  52: {
    a: "Call the payment service after approval but generate a new request identifier whenever a timed-out call is retried",
    b: "Treat an approved model confidence threshold as payment authorization and query the backend after execution",
    d: "Pause for adjuster approval, then call the payment service without an idempotency key and disable automatic retries",
  },
  54: {
    a: "Run continuous real-time recognition workers for every stored recording until the entire archive completes",
    b: "Use fast transcription for each complete recording and coordinate the synchronous requests in application code",
    c: "Use conversation transcription sessions for the stored files and keep every session open until processing finishes",
  },
  55: {
    a: "Use a layout analyzer without a business-field schema and infer all claim values later from plain text",
    e: "Declare the required field schema but disable detailed output so confidence and source locations are omitted",
  },
  56: {
    a: "Data Zone Standard with pay-per-token capacity and dynamic quota enabled",
    b: "Regional Provisioned in one EU region without the required EU data-zone deployment scope",
    d: "Global Provisioned with reserved capacity that can process requests outside the EU data zone",
  },
  57: {
    b: "Store a permanent function key in the project connection and restrict the tool through its OpenAPI description",
    e: "Describe argument limits in the agent instructions and let the model bypass backend validation after confirmation",
  },
  58: {
    b: "Use OCR on panel labels, retrieve the matching manual page, and infer the light state without visual reasoning",
    c: "Train an object detector for warning lights and always return the detected class without an uncertainty path",
    d: "Use a multimodal model with the image and manual but require it to choose Yes or No even when evidence is missing",
  },
  60: {
    a: "Full-text search that preserves exact matches for error codes and part identifiers",
    b: "Vector search that retrieves instructions with conceptually similar technical meaning",
    c: "A pre-scoring filter for equipment family, approval state, and effective revision",
    d: "Semantic reranking applied after reciprocal-rank fusion of keyword and vector results",
    e: "Use semantic keyword search without vectors and boost every document from the selected equipment family",
    f: "Use hybrid retrieval but apply the equipment and revision authorization filters only after vector scoring",
  },
  62: {
    a: "Write separate traces for retrieval, each specialist, and publication without propagating a parent context",
    c: "Record daily average latency for retrieval, models, and tools without retaining individual campaign traces",
    d: "Trace only the orchestrator model call and ask each specialist to summarize its own latency in the final output",
  },
  63: {
    b: "Use a masked GPT-image edit with low input fidelity so the seasonal background can vary more freely",
    c: "Generate a new image from the product name and use a fixed seed to approximate the approved photograph",
    d: "Create an unmasked image variation and rely on the prompt to preserve the logo and printed disclosure",
  },
  64: {
    a: "Detected tone and sentiment represented in the declared campaign-review output",
    b: "Extracted product names and disclosure references that can be checked against policy",
    c: "A localized campaign summary that conforms to the downstream JSON schema",
    d: "Run built-in sentiment analysis only and use the sentiment label as the complete copy-review result",
    e: "Request a structured summary but omit retrieved disclosure text and product identifiers from the model context",
  },
  65: {
    b: "Use standard Video Indexer insights without defining the campaign-specific fields or grounding contract",
    c: "Combine batch Speech transcription with OCR on sampled frames and discard the common segment timeline",
    d: "Store one embedding per video and ask a model to infer the time interval represented by each result",
  },
  66: {
    b: "Enable dynamic quota and create the full 100,000-TPM deployment without changing the existing allocations",
    c: "Create the deployment in another Foundry project that uses the same subscription, model, and regional quota pool",
    d: "Change the deployment to Global Standard while assuming the regional Standard quota automatically transfers",
  },
  70: {
    a: "Reader at subscription scope",
    b: "Foundry User at each project scope",
    d: "Cognitive Services Contributor at subscription scope",
  },
  71: {
    e: "Deploy the change to all production traffic before running the representative regression dataset",
    f: "Run the pipeline evaluation but allow unversioned prompt and index changes directly in the production portal",
  },
  72: {
    b: "Tune thresholds only on adversarial examples and use the setting with the highest block rate",
    c: "Set every category to the most restrictive threshold without testing normal business content",
    d: "Use the service defaults permanently and monitor only the number of requests that receive HTTP errors",
  },
  73: {
    a: "Indexer completion status, failed documents, and detailed enrichment-skill errors",
    b: "Document freshness, indexed counts, and delay in processing updates or deletions",
    c: "Embedding coverage plus vector dimension, generation, and field-mapping failures",
    d: "Retrieval relevance measured repeatedly against a stable representative query set",
    e: "Model-deployment quota and token utilization without ingestion or retrieval measurements",
    f: "Portal availability and administrator sign-in counts without document or query quality signals",
  },
  74: {
    d: "Use an approved project connection but give the agent access to every MCP tool under a subscription-level owner identity",
    e: "Require approval for the first call to each MCP tool, then treat that tool as trusted for every later user and argument",
  },
  75: {
    b: "Each callable operation defines a unique operationRef while operationId is omitted",
    c: "Each callable operation has a unique tag and summary but shares the same operationId",
    d: "The servers array contains the production URL even though callable operations don't define operationId",
  },
  77: {
    b: "Generate a new idempotency key for each retry so every HTTP request can be traced separately",
    c: "Query for an existing label before each retry, then issue an unkeyed create request when none is returned",
    d: "Ask the model whether the first call probably succeeded and retry only when its confidence is low",
  },
  78: {
    d: "Prompt the model to include plausible source URLs and accept them whenever the URL format is valid",
    e: "Keep the document URL but omit chunk identifiers and effective-version metadata from retrieval results",
  },
  80: {
    b: "Route by prompt length alone, sending short prompts to the small model and long prompts to the reasoning model",
    c: "Send every request to the small model and escalate only after an HTTP or parsing failure",
    d: "Send every request to the strongest model and reduce cost by limiting all responses to the same token count",
  },
  81: {
    b: "Use JSON mode, parse the response, and accept any syntactically valid object",
    c: "Use function calling and treat the emitted arguments as the final API response without schema validation",
    d: "Request the schema in the prompt and retry with a stronger instruction whenever a property is missing",
  },
  83: {
    e: "Aggregate model latency and total token cost for the release without retaining per-operation spans",
    f: "Store raw prompts and final answers but omit workflow, tool-schema, index, and deployment versions",
  },
  84: {
    b: "A DALL-E 3 deployment created after its new-deployment retirement date",
    c: "A vision-capable chat model that accepts images but doesn't expose an image-generation operation",
    d: "An image-embedding model used to retrieve the nearest existing asset",
  },
  85: {
    b: "Request a transparent background with JPEG output",
    c: "Request an opaque background with PNG output",
    d: "Leave the background on auto and request JPEG output",
  },
  86: {
    d: "Return every generated image as a hosted URL instead of inline base64 data",
    e: "Request a transparent background while using JPEG output",
  },
  89: {
    b: "Train a custom Speech model on labeled recordings of the twelve names before the live demo",
    c: "Use pronunciation assessment to score each recognized product name and substitute low-scoring results",
    d: "Create a custom neural voice that pronounces the product names correctly during text-to-speech output",
  },
  90: {
    a: "Pronunciation through SSML phonemes or a referenced pronunciation lexicon",
    b: "Pauses, emphasis, and sentence delivery through SSML prosody elements",
    c: "Voice selection together with speaking rate, pitch, volume, and other prosody controls",
    d: "The audio container, codec, and sample rate selected for the synthesized output file",
    e: "The Azure region and deployment capacity assigned to a custom voice endpoint",
  },
  91: {
    b: "Extract every paragraph, call Text Translation, and rebuild each Word or PDF layout in application code",
    c: "Use Speech Translation after converting every document page to synthesized audio",
    d: "Use a multilingual language model to rewrite each file and infer the original document structure",
  },
  92: {
    b: "Use only indexer fieldMappings to copy the parent document into one target search document",
    c: "Use outputFieldMappings for enriched values but omit the index projection that creates child documents",
    d: "Store one search document per manual with all chunks in a collection field and no repeated parent fields",
  },
  93: {
    d: "Declare the field schema but disable detailed output and discard confidence and source locations",
    e: "Use a layout-only analyzer without the custom business fields required by downstream automation",
  },
  94: {
    a: "preFilter, so the tenant predicate runs before vector candidate scoring",
    b: "postFilter, which applies the tenant predicate after vector candidates have been selected",
    c: "strictPostFilter, which filters only the final global top-k vector results",
    d: "No service filter; include the tenant rule in the grounding prompt after retrieval",
  },
  100: {
    b: "An Azure OpenAI resource that hosts only model deployments and OpenAI-compatible inference endpoints",
    c: "A Foundry project created without a parent Foundry resource boundary",
    d: "A classic Foundry hub used as the shared resource for all new Foundry capabilities",
  },
  102: {
    b: "Foundry User at the project scope",
    c: "Azure AI User at the Foundry resource scope",
    d: "Reader at the individual agent scope",
  },
  103: {
    b: "Whether the principal has Reader at the project scope but no Foundry data-plane role",
    c: "Whether the same token should instead use the Azure Resource Manager audience for the project request",
    d: "Whether the principal has Search Index Data Reader only on the connected search service",
  },
  104: {
    b: "Create an equivalent project-level connection in every project and give each team Contributor on the Foundry resource",
    c: "Create one resource-level key connection and give every project team Foundry Owner so they can resolve and edit it",
    d: "Create a managed-identity connection in every project and let the central team update each copy independently",
  },
  105: {
    b: "A service SAS signed with the Storage account key and limited to read access for 15 minutes",
    c: "An account SAS signed with the Storage account key and limited to Blob service read access",
    d: "A Microsoft Entra bearer token copied into the URL for the reviewer to reuse during the 15-minute period",
  },
  106: {
    c: "Create private endpoints but continue resolving each service name to its public address",
    d: "Use service endpoints and resource firewalls while keeping both services on public endpoints",
  },
  111: {
    b: "Assign Foundry User at the full Foundry resource scope",
    c: "Assign Reader at the individual agent scope",
    d: "Assign Search Index Data Reader on the agent's connected search service",
  },
  112: {
    b: "Quarantine the passage but send an automatically generated summary of it to the agent as trusted context",
    c: "Keep the passage when a normal harm-category analysis returns low severity after the Prompt Shields detection",
    d: "Move the passage into the system-message section so its instructions are evaluated at a higher priority",
  },
  113: {
    b: "Retry at a fixed one-second interval for three attempts, even when Retry-After requests a longer delay",
    c: "Immediately switch to another deployment in the same quota pool before retrying the request",
    d: "Place the request on an unbounded retry queue until the original deployment accepts it",
  },
  116: {
    b: "A 512 × 512 mask with the same aspect ratio, relying on the service to scale it to the source image",
    c: "A 1024 × 1024 mask whose selected pixels identify the area that must remain unchanged",
    d: "A 1024 × 768 mask that covers only the visible foreground portion of the square source image",
  },
  117: {
    b: "Use standard Video Indexer insights and discard any intervals that don't contain recognized speech",
    c: "Combine batch Speech timestamps with OCR from one frame every minute and infer the shared intervals",
    d: "Ask a multimodal model for one video-level answer and retain only the final text and asset URL",
  },
  120: {
    b: "Regenerate the West Europe key and continue sending it to the East US regional endpoint",
    c: "Use the global Speech endpoint with the regional key but omit the resource region from configuration",
    d: "Acquire a token for an East US Speech resource while continuing to identify the West Europe resource in the request",
  },
  121: {
    a: "Azure Speech batch transcription for asynchronous processing of the Blob-hosted recordings",
    b: "Fast transcription, submitting each complete long recording through a synchronous request",
    c: "Continuous real-time recognition, with one long-running recognizer allocated to every Blob recording",
    d: "Conversation transcription, with a live session kept open while each stored file is played into it",
  },
  122: {
    b: "A Document Intelligence custom neural model trained on labeled copies of the common invoice format",
    c: "A Document Intelligence custom template model trained separately for every vendor layout",
    d: "A custom Content Understanding analyzer with natural-language fields matching the standard invoice schema",
  },
  123: {
    b: "A Document Intelligence custom neural model trained separately for letters, photographs, recordings, and PDFs",
    c: "A composed Document Intelligence model containing one labeled extraction model for every incoming modality",
    d: "A routing pipeline of prebuilt document models, OCR, and Speech with application-written rules for all inferred fields",
  },
  128: {
    b: "Change filterable to true in the existing index definition and rerun the indexer without rebuilding documents",
    c: "Create an index alias for the existing index and set the alias itself to filterable",
    d: "Keep the field nonfilterable and enforce the tenant predicate in a semantic configuration",
  },
  129: {
    b: "Train a Document Intelligence custom template model and require every visual variant to use identical field positions",
    c: "Create a composed model containing only prebuilt models and route by the application's form name",
    d: "Train a custom classifier to identify each visual variant, then use prebuilt layout without custom field extraction",
  },
  130: {
    d: "Declare the fields but disable detailed output so confidence and source grounding aren't retained",
    e: "Return one free-form text field and let downstream code infer every business value without typed declarations",
  },
};
